// <auto-generated />
#nullable enable
#pragma warning disable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.OpenGenericImposter;

namespace Imposter.Tests.Features.OpenGenericImposter
{
    [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
    public sealed class IHaveIndexerImposter<T> : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>> where T : class
    {
        private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
        private ImposterTargetInstance _imposterInstance;
        global::Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T> global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>>.Instance()
        {
            return _imposterInstance;
        }

        private readonly IndexerIndexerBuilder _IndexerIndexer;
        public IIndexerIndexerBuilder this[global::Imposter.Abstractions.Arg<int> index] => new IndexerIndexerBuilder.InvocationBuilder(_IndexerIndexer, new IndexerIndexerArgumentsCriteria(index));
        public delegate T IndexerIndexerDelegate(int index);
        public delegate void IndexerIndexerGetterCallback(int index);
        public delegate void IndexerIndexerSetterCallback(int index, T value);
        public delegate global::System.Exception IndexerIndexerExceptionGenerator(int index);
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class IndexerIndexerArguments : global::System.IEquatable<IndexerIndexerArguments>
        {
            public int index;
            internal IndexerIndexerArguments(int index)
            {
                this.index = index;
            }

            public bool Equals(IndexerIndexerArguments? other)
            {
                if (other == null)
                {
                    return false;
                }

                return true && (index == other.index);
            }

            public override bool Equals(object? obj)
            {
                return obj is IndexerIndexerArguments other && Equals(other);
            }

            public override int GetHashCode()
            {
                global::System.HashCode hash = new global::System.HashCode();
                hash.Add(index);
                return hash.ToHashCode();
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class IndexerIndexerArgumentsCriteria
        {
            public global::Imposter.Abstractions.Arg<int> index;
            internal IndexerIndexerArgumentsCriteria(global::Imposter.Abstractions.Arg<int> index)
            {
                this.index = index;
            }

            public bool Matches(IndexerIndexerArguments arguments)
            {
                return index.Matches(arguments.index);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class IndexerIndexerBuilder
        {
            private readonly DefaultIndexerIndexerBehaviour _IndexerDefaultIndexerBehaviour = new DefaultIndexerIndexerBehaviour();
            private readonly GetterImposter _getterImposter;
            private readonly SetterImposter _setterImposter;
            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultIndexerIndexerBehaviour
            {
                private bool _isOn = true;
                internal bool IsOn
                {
                    get
                    {
                        return global::System.Threading.Volatile.Read(ref _isOn);
                    }

                    set
                    {
                        global::System.Threading.Volatile.Write(ref _isOn, value);
                    }
                }

                internal global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArguments, T> BackingField = new global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArguments, T>();
                internal T Get(IndexerIndexerArguments arguments, global::System.Func<T>? baseImplementation = null)
                {
                    T value = default(T);
                    if (BackingField.TryGetValue(arguments, out value))
                        return value;
                    if (baseImplementation != null)
                        return baseImplementation();
                    return default(T);
                }

                internal void Set(IndexerIndexerArguments arguments, T value, global::System.Action? baseImplementation = null)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                        return;
                    }

                    BackingField[arguments] = value;
                }
            }

            internal IndexerIndexerBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
            {
                this._getterImposter = new GetterImposter(_IndexerDefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
                this._setterImposter = new SetterImposter(_IndexerDefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
            }

            internal IIndexerIndexerGetterBuilder CreateGetter(IndexerIndexerArgumentsCriteria criteria)
            {
                return new GetterImposter.Builder(_getterImposter, criteria);
            }

            internal IIndexerIndexerSetterBuilder CreateSetter(IndexerIndexerArgumentsCriteria criteria)
            {
                _setterImposter.MarkConfigured();
                return new SetterImposter.Builder(_setterImposter, criteria);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class InvocationBuilder : IIndexerIndexerBuilder
            {
                private readonly IndexerIndexerBuilder _builder;
                private readonly IndexerIndexerArgumentsCriteria _criteria;
                internal InvocationBuilder(IndexerIndexerBuilder builder, IndexerIndexerArgumentsCriteria criteria)
                {
                    this._builder = builder;
                    this._criteria = criteria;
                }

                public IIndexerIndexerGetterBuilder Getter()
                {
                    return _builder.CreateGetter(_criteria);
                }

                public IIndexerIndexerSetterBuilder Setter()
                {
                    return _builder.CreateSetter(_criteria);
                }
            }

            internal T Get(int index)
            {
                return _getterImposter.Get(index);
            }

            internal void Set(int index, T value)
            {
                _setterImposter.Set(index, value, null);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class GetterImposter
            {
                private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
                private readonly global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter> _getterInvocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArgumentsCriteria, GetterInvocationImposter> _setupLookup = new global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArgumentsCriteria, GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<IndexerIndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<IndexerIndexerArguments>();
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredReturn;
                internal GetterImposter(DefaultIndexerIndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                internal T Get(int index, global::System.Func<T>? baseImplementation = null)
                {
                    IndexerIndexerArguments arguments = new IndexerIndexerArguments(index);
                    try
                    {
                        var getterInvocationImposter = FindGetterInvocationImposter(arguments);
                        if (getterInvocationImposter is null)
                        {
                            EnsureGetterConfigured();
                            if (_defaultBehaviour.IsOn)
                                return _defaultBehaviour.Get(arguments, baseImplementation);
                            if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }
                            else
                            {
                                return default(T);
                            }
                        }

                        return getterInvocationImposter.Invoke(arguments, baseImplementation);
                    }
                    finally
                    {
                        _invocationHistory.Add(arguments);
                    }
                }

                private GetterInvocationImposter? FindGetterInvocationImposter(IndexerIndexerArguments arguments)
                {
                    foreach (var getterInvocationImposter in _getterInvocationImposters)
                    {
                        if (getterInvocationImposter.Criteria.Matches(arguments))
                        {
                            return getterInvocationImposter;
                        }
                    }

                    return null;
                }

                private GetterInvocationImposter GetOrCreate(IndexerIndexerArgumentsCriteria criteria)
                {
                    return _setupLookup.GetOrAdd(criteria, CreateSetup);
                    GetterInvocationImposter CreateSetup(IndexerIndexerArgumentsCriteria key)
                    {
                        GetterInvocationImposter getterInvocationImposter = new GetterInvocationImposter(this, _defaultBehaviour, key);
                        _getterInvocationImposters.Push(getterInvocationImposter);
                        return getterInvocationImposter;
                    }
                }

                private void Called(IndexerIndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal string PropertyDisplayName => _propertyDisplayName;

                internal void MarkReturnConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredReturn, true);
                }

                private void EnsureGetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredReturn))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexerIndexerGetterBuilder, IIndexerIndexerGetterFluentBuilder
                {
                    private readonly GetterImposter _imposter;
                    private readonly IndexerIndexerArgumentsCriteria _criteria;
                    internal Builder(GetterImposter _imposter, IndexerIndexerArgumentsCriteria _criteria)
                    {
                        this._imposter = _imposter;
                        this._criteria = _criteria;
                    }

                    private GetterInvocationImposter InvocationImposter => _imposter.GetOrCreate(_criteria);

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(T value)
                    {
                        InvocationImposter.AddReturnValue(arguments => value);
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(global::System.Func<T> valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator());
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(IndexerIndexerDelegate valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator(arguments.index));
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws(global::System.Exception exception)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exception);
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws<TException>()
                    {
                        InvocationImposter.AddReturnValue(arguments => throw new TException());
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws(IndexerIndexerExceptionGenerator exceptionGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exceptionGenerator(arguments.index));
                        return this;
                    }

                    IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterCallbackBuilder.Callback(IndexerIndexerGetterCallback callback)
                    {
                        InvocationImposter.AddCallback(callback);
                        return this;
                    }

                    void IIndexerIndexerGetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _imposter.Called(_criteria, count);
                    }

                    IIndexerIndexerGetterFluentBuilder IIndexerIndexerGetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                private sealed class GetterInvocationImposter
                {
                    private readonly GetterImposter _parent;
                    private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<IndexerIndexerArguments, global::System.Func<T>, T>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<IndexerIndexerArguments, global::System.Func<T>, T>>();
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerGetterCallback> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerGetterCallback>();
                    private volatile global::System.Func<IndexerIndexerArguments, global::System.Func<T>, T>? _lastReturnValue;
                    private int _invocationCount;
                    private string _propertyDisplayName;
                    internal IndexerIndexerArgumentsCriteria Criteria { get; private set; }
                    internal int InvocationCount => global::System.Threading.Volatile.Read(ref _invocationCount);

                    internal GetterInvocationImposter(GetterImposter parent, DefaultIndexerIndexerBehaviour defaultBehaviour, IndexerIndexerArgumentsCriteria criteria)
                    {
                        this._parent = parent;
                        this._defaultBehaviour = defaultBehaviour;
                        this._propertyDisplayName = parent.PropertyDisplayName;
                        this.Criteria = criteria;
                    }

                    internal void AddReturnValue(global::System.Func<IndexerIndexerArguments, T> generator)
                    {
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) => generator(arguments));
                        _parent.MarkReturnConfigured();
                    }

                    internal void AddCallback(IndexerIndexerGetterCallback callback)
                    {
                        _callbacks.Enqueue(callback);
                    }

                    internal T Invoke(IndexerIndexerArguments arguments, global::System.Func<T>? baseImplementation = null)
                    {
                        global::System.Threading.Interlocked.Increment(ref _invocationCount);
                        foreach (var callback in _callbacks)
                        {
                            callback(arguments.index);
                        }

                        global::System.Func<IndexerIndexerArguments, global::System.Func<T>, T> generator = ResolveNextGenerator(arguments);
                        return generator(arguments, baseImplementation);
                    }

                    private global::System.Func<IndexerIndexerArguments, global::System.Func<T>, T> ResolveNextGenerator(IndexerIndexerArguments arguments)
                    {
                        if (_defaultBehaviour.IsOn)
                        {
                            return (arguments, baseImplementation) => _defaultBehaviour.Get(arguments, baseImplementation);
                        }

                        _returnValues.TryDequeue(out var returnValue);
                        var nextReturnValue = returnValue ?? _lastReturnValue;
                        if (nextReturnValue == null)
                        {
                            throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                        }

                        _lastReturnValue = nextReturnValue;
                        return nextReturnValue!;
                    }

                    internal void UseBaseImplementation()
                    {
                        _parent.MarkReturnConfigured();
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) =>
                        {
                            if (baseImplementation == null)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }

                            return baseImplementation();
                        });
                        _lastReturnValue = null;
                    }
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class SetterImposter
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<(IndexerIndexerArgumentsCriteria Criteria, IndexerIndexerSetterCallback Callback)> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<(IndexerIndexerArgumentsCriteria Criteria, IndexerIndexerSetterCallback Callback)>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<IndexerIndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<IndexerIndexerArguments>();
                private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredSetter;
                internal SetterImposter(DefaultIndexerIndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                public void Callback(IndexerIndexerArgumentsCriteria criteria, IndexerIndexerSetterCallback callback)
                {
                    _callbacks.Enqueue((criteria, callback));
                }

                public void Called(IndexerIndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal void Set(int index, T value, global::System.Action? baseImplementation = null)
                {
                    EnsureSetterConfigured();
                    IndexerIndexerArguments arguments = new IndexerIndexerArguments(index);
                    _invocationHistory.Add(arguments);
                    bool matchedCallback = false;
                    foreach (var registration in _callbacks)
                    {
                        if (registration.Criteria.Matches(arguments))
                        {
                            registration.Callback(arguments.index, value);
                            matchedCallback = true;
                        }
                    }

                    if (!matchedCallback && _defaultBehaviour.IsOn)
                    {
                        _defaultBehaviour.Set(arguments, value, null);
                    }
                }

                private void EnsureSetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredSetter))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
                    }
                }

                internal void MarkConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredSetter, true);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexerIndexerSetterBuilder, IIndexerIndexerSetterFluentBuilder
                {
                    private readonly SetterImposter _setterImposter;
                    private readonly IndexerIndexerArgumentsCriteria _criteria;
                    internal Builder(SetterImposter _setterImposter, IndexerIndexerArgumentsCriteria _criteria)
                    {
                        this._setterImposter = _setterImposter;
                        this._criteria = _criteria;
                    }

                    IIndexerIndexerSetterContinuationBuilder IIndexerIndexerSetterCallbackBuilder.Callback(IndexerIndexerSetterCallback callback)
                    {
                        _setterImposter.Callback(_criteria, callback);
                        return this;
                    }

                    void IIndexerIndexerSetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _setterImposter.Called(_criteria, count);
                    }

                    IIndexerIndexerSetterFluentBuilder IIndexerIndexerSetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterOutcomeBuilder
        {
            IIndexerIndexerGetterContinuationBuilder Returns(T value);
            IIndexerIndexerGetterContinuationBuilder Returns(global::System.Func<T> valueGenerator);
            IIndexerIndexerGetterContinuationBuilder Returns(IndexerIndexerDelegate valueGenerator);
            IIndexerIndexerGetterContinuationBuilder Throws(global::System.Exception exception);
            IIndexerIndexerGetterContinuationBuilder Throws<TException>()
                where TException : Exception, new();
            IIndexerIndexerGetterContinuationBuilder Throws(IndexerIndexerExceptionGenerator exceptionGenerator);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterCallbackBuilder
        {
            IIndexerIndexerGetterContinuationBuilder Callback(IndexerIndexerGetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterContinuationBuilder : IIndexerIndexerGetterCallbackBuilder
        {
            IIndexerIndexerGetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterFluentBuilder : IIndexerIndexerGetterOutcomeBuilder, IIndexerIndexerGetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerGetterBuilder : IIndexerIndexerGetterOutcomeBuilder, IIndexerIndexerGetterCallbackBuilder, IIndexerIndexerGetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerSetterCallbackBuilder
        {
            IIndexerIndexerSetterContinuationBuilder Callback(IndexerIndexerSetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerSetterContinuationBuilder : IIndexerIndexerSetterCallbackBuilder
        {
            IIndexerIndexerSetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerSetterFluentBuilder : IIndexerIndexerSetterCallbackBuilder, IIndexerIndexerSetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerSetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerSetterBuilder : IIndexerIndexerSetterCallbackBuilder, IIndexerIndexerSetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexerIndexerBuilder
        {
            IIndexerIndexerGetterBuilder Getter();
            IIndexerIndexerSetterBuilder Setter();
        }

        private readonly Indexer_1IndexerBuilder _Indexer_1Indexer;
        public IIndexer_1IndexerBuilder this[global::Imposter.Abstractions.Arg<T> key] => new Indexer_1IndexerBuilder.InvocationBuilder(_Indexer_1Indexer, new Indexer_1IndexerArgumentsCriteria(key));
        public delegate int Indexer_1IndexerDelegate(T key);
        public delegate void Indexer_1IndexerGetterCallback(T key);
        public delegate void Indexer_1IndexerSetterCallback(T key, int value);
        public delegate global::System.Exception Indexer_1IndexerExceptionGenerator(T key);
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_1IndexerArguments : global::System.IEquatable<Indexer_1IndexerArguments>
        {
            public T key;
            internal Indexer_1IndexerArguments(T key)
            {
                this.key = key;
            }

            public bool Equals(Indexer_1IndexerArguments? other)
            {
                if (other == null)
                {
                    return false;
                }

                return true && (key == other.key);
            }

            public override bool Equals(object? obj)
            {
                return obj is Indexer_1IndexerArguments other && Equals(other);
            }

            public override int GetHashCode()
            {
                global::System.HashCode hash = new global::System.HashCode();
                hash.Add(key);
                return hash.ToHashCode();
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_1IndexerArgumentsCriteria
        {
            public global::Imposter.Abstractions.Arg<T> key;
            internal Indexer_1IndexerArgumentsCriteria(global::Imposter.Abstractions.Arg<T> key)
            {
                this.key = key;
            }

            public bool Matches(Indexer_1IndexerArguments arguments)
            {
                return key.Matches(arguments.key);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_1IndexerBuilder
        {
            private readonly DefaultIndexer_1IndexerBehaviour _Indexer_1DefaultIndexerBehaviour = new DefaultIndexer_1IndexerBehaviour();
            private readonly GetterImposter _getterImposter;
            private readonly SetterImposter _setterImposter;
            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultIndexer_1IndexerBehaviour
            {
                private bool _isOn = true;
                internal bool IsOn
                {
                    get
                    {
                        return global::System.Threading.Volatile.Read(ref _isOn);
                    }

                    set
                    {
                        global::System.Threading.Volatile.Write(ref _isOn, value);
                    }
                }

                internal global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_1IndexerArguments, int> BackingField = new global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_1IndexerArguments, int>();
                internal int Get(Indexer_1IndexerArguments arguments, global::System.Func<int>? baseImplementation = null)
                {
                    int value = default(int);
                    if (BackingField.TryGetValue(arguments, out value))
                        return value;
                    if (baseImplementation != null)
                        return baseImplementation();
                    return default(int);
                }

                internal void Set(Indexer_1IndexerArguments arguments, int value, global::System.Action? baseImplementation = null)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                        return;
                    }

                    BackingField[arguments] = value;
                }
            }

            internal Indexer_1IndexerBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
            {
                this._getterImposter = new GetterImposter(_Indexer_1DefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
                this._setterImposter = new SetterImposter(_Indexer_1DefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
            }

            internal IIndexer_1IndexerGetterBuilder CreateGetter(Indexer_1IndexerArgumentsCriteria criteria)
            {
                return new GetterImposter.Builder(_getterImposter, criteria);
            }

            internal IIndexer_1IndexerSetterBuilder CreateSetter(Indexer_1IndexerArgumentsCriteria criteria)
            {
                _setterImposter.MarkConfigured();
                return new SetterImposter.Builder(_setterImposter, criteria);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class InvocationBuilder : IIndexer_1IndexerBuilder
            {
                private readonly Indexer_1IndexerBuilder _builder;
                private readonly Indexer_1IndexerArgumentsCriteria _criteria;
                internal InvocationBuilder(Indexer_1IndexerBuilder builder, Indexer_1IndexerArgumentsCriteria criteria)
                {
                    this._builder = builder;
                    this._criteria = criteria;
                }

                public IIndexer_1IndexerGetterBuilder Getter()
                {
                    return _builder.CreateGetter(_criteria);
                }

                public IIndexer_1IndexerSetterBuilder Setter()
                {
                    return _builder.CreateSetter(_criteria);
                }
            }

            internal int Get(T key)
            {
                return _getterImposter.Get(key);
            }

            internal void Set(T key, int value)
            {
                _setterImposter.Set(key, value, null);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class GetterImposter
            {
                private readonly DefaultIndexer_1IndexerBehaviour _defaultBehaviour;
                private readonly global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter> _getterInvocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_1IndexerArgumentsCriteria, GetterInvocationImposter> _setupLookup = new global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_1IndexerArgumentsCriteria, GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<Indexer_1IndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<Indexer_1IndexerArguments>();
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredReturn;
                internal GetterImposter(DefaultIndexer_1IndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                internal int Get(T key, global::System.Func<int>? baseImplementation = null)
                {
                    Indexer_1IndexerArguments arguments = new Indexer_1IndexerArguments(key);
                    try
                    {
                        var getterInvocationImposter = FindGetterInvocationImposter(arguments);
                        if (getterInvocationImposter is null)
                        {
                            EnsureGetterConfigured();
                            if (_defaultBehaviour.IsOn)
                                return _defaultBehaviour.Get(arguments, baseImplementation);
                            if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }
                            else
                            {
                                return default(int);
                            }
                        }

                        return getterInvocationImposter.Invoke(arguments, baseImplementation);
                    }
                    finally
                    {
                        _invocationHistory.Add(arguments);
                    }
                }

                private GetterInvocationImposter? FindGetterInvocationImposter(Indexer_1IndexerArguments arguments)
                {
                    foreach (var getterInvocationImposter in _getterInvocationImposters)
                    {
                        if (getterInvocationImposter.Criteria.Matches(arguments))
                        {
                            return getterInvocationImposter;
                        }
                    }

                    return null;
                }

                private GetterInvocationImposter GetOrCreate(Indexer_1IndexerArgumentsCriteria criteria)
                {
                    return _setupLookup.GetOrAdd(criteria, CreateSetup);
                    GetterInvocationImposter CreateSetup(Indexer_1IndexerArgumentsCriteria key)
                    {
                        GetterInvocationImposter getterInvocationImposter = new GetterInvocationImposter(this, _defaultBehaviour, key);
                        _getterInvocationImposters.Push(getterInvocationImposter);
                        return getterInvocationImposter;
                    }
                }

                private void Called(Indexer_1IndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal string PropertyDisplayName => _propertyDisplayName;

                internal void MarkReturnConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredReturn, true);
                }

                private void EnsureGetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredReturn))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexer_1IndexerGetterBuilder, IIndexer_1IndexerGetterFluentBuilder
                {
                    private readonly GetterImposter _imposter;
                    private readonly Indexer_1IndexerArgumentsCriteria _criteria;
                    internal Builder(GetterImposter _imposter, Indexer_1IndexerArgumentsCriteria _criteria)
                    {
                        this._imposter = _imposter;
                        this._criteria = _criteria;
                    }

                    private GetterInvocationImposter InvocationImposter => _imposter.GetOrCreate(_criteria);

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Returns(int value)
                    {
                        InvocationImposter.AddReturnValue(arguments => value);
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Returns(global::System.Func<int> valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator());
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Returns(Indexer_1IndexerDelegate valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator(arguments.key));
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Throws(global::System.Exception exception)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exception);
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Throws<TException>()
                    {
                        InvocationImposter.AddReturnValue(arguments => throw new TException());
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterOutcomeBuilder.Throws(Indexer_1IndexerExceptionGenerator exceptionGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exceptionGenerator(arguments.key));
                        return this;
                    }

                    IIndexer_1IndexerGetterContinuationBuilder IIndexer_1IndexerGetterCallbackBuilder.Callback(Indexer_1IndexerGetterCallback callback)
                    {
                        InvocationImposter.AddCallback(callback);
                        return this;
                    }

                    void IIndexer_1IndexerGetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _imposter.Called(_criteria, count);
                    }

                    IIndexer_1IndexerGetterFluentBuilder IIndexer_1IndexerGetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                private sealed class GetterInvocationImposter
                {
                    private readonly GetterImposter _parent;
                    private readonly DefaultIndexer_1IndexerBehaviour _defaultBehaviour;
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<Indexer_1IndexerArguments, global::System.Func<int>, int>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<Indexer_1IndexerArguments, global::System.Func<int>, int>>();
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<Indexer_1IndexerGetterCallback> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<Indexer_1IndexerGetterCallback>();
                    private volatile global::System.Func<Indexer_1IndexerArguments, global::System.Func<int>, int>? _lastReturnValue;
                    private int _invocationCount;
                    private string _propertyDisplayName;
                    internal Indexer_1IndexerArgumentsCriteria Criteria { get; private set; }
                    internal int InvocationCount => global::System.Threading.Volatile.Read(ref _invocationCount);

                    internal GetterInvocationImposter(GetterImposter parent, DefaultIndexer_1IndexerBehaviour defaultBehaviour, Indexer_1IndexerArgumentsCriteria criteria)
                    {
                        this._parent = parent;
                        this._defaultBehaviour = defaultBehaviour;
                        this._propertyDisplayName = parent.PropertyDisplayName;
                        this.Criteria = criteria;
                    }

                    internal void AddReturnValue(global::System.Func<Indexer_1IndexerArguments, int> generator)
                    {
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) => generator(arguments));
                        _parent.MarkReturnConfigured();
                    }

                    internal void AddCallback(Indexer_1IndexerGetterCallback callback)
                    {
                        _callbacks.Enqueue(callback);
                    }

                    internal int Invoke(Indexer_1IndexerArguments arguments, global::System.Func<int>? baseImplementation = null)
                    {
                        global::System.Threading.Interlocked.Increment(ref _invocationCount);
                        foreach (var callback in _callbacks)
                        {
                            callback(arguments.key);
                        }

                        global::System.Func<Indexer_1IndexerArguments, global::System.Func<int>, int> generator = ResolveNextGenerator(arguments);
                        return generator(arguments, baseImplementation);
                    }

                    private global::System.Func<Indexer_1IndexerArguments, global::System.Func<int>, int> ResolveNextGenerator(Indexer_1IndexerArguments arguments)
                    {
                        if (_defaultBehaviour.IsOn)
                        {
                            return (arguments, baseImplementation) => _defaultBehaviour.Get(arguments, baseImplementation);
                        }

                        _returnValues.TryDequeue(out var returnValue);
                        var nextReturnValue = returnValue ?? _lastReturnValue;
                        if (nextReturnValue == null)
                        {
                            throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                        }

                        _lastReturnValue = nextReturnValue;
                        return nextReturnValue!;
                    }

                    internal void UseBaseImplementation()
                    {
                        _parent.MarkReturnConfigured();
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) =>
                        {
                            if (baseImplementation == null)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }

                            return baseImplementation();
                        });
                        _lastReturnValue = null;
                    }
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class SetterImposter
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<(Indexer_1IndexerArgumentsCriteria Criteria, Indexer_1IndexerSetterCallback Callback)> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<(Indexer_1IndexerArgumentsCriteria Criteria, Indexer_1IndexerSetterCallback Callback)>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<Indexer_1IndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<Indexer_1IndexerArguments>();
                private readonly DefaultIndexer_1IndexerBehaviour _defaultBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredSetter;
                internal SetterImposter(DefaultIndexer_1IndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                public void Callback(Indexer_1IndexerArgumentsCriteria criteria, Indexer_1IndexerSetterCallback callback)
                {
                    _callbacks.Enqueue((criteria, callback));
                }

                public void Called(Indexer_1IndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal void Set(T key, int value, global::System.Action? baseImplementation = null)
                {
                    EnsureSetterConfigured();
                    Indexer_1IndexerArguments arguments = new Indexer_1IndexerArguments(key);
                    _invocationHistory.Add(arguments);
                    bool matchedCallback = false;
                    foreach (var registration in _callbacks)
                    {
                        if (registration.Criteria.Matches(arguments))
                        {
                            registration.Callback(arguments.key, value);
                            matchedCallback = true;
                        }
                    }

                    if (!matchedCallback && _defaultBehaviour.IsOn)
                    {
                        _defaultBehaviour.Set(arguments, value, null);
                    }
                }

                private void EnsureSetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredSetter))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
                    }
                }

                internal void MarkConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredSetter, true);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexer_1IndexerSetterBuilder, IIndexer_1IndexerSetterFluentBuilder
                {
                    private readonly SetterImposter _setterImposter;
                    private readonly Indexer_1IndexerArgumentsCriteria _criteria;
                    internal Builder(SetterImposter _setterImposter, Indexer_1IndexerArgumentsCriteria _criteria)
                    {
                        this._setterImposter = _setterImposter;
                        this._criteria = _criteria;
                    }

                    IIndexer_1IndexerSetterContinuationBuilder IIndexer_1IndexerSetterCallbackBuilder.Callback(Indexer_1IndexerSetterCallback callback)
                    {
                        _setterImposter.Callback(_criteria, callback);
                        return this;
                    }

                    void IIndexer_1IndexerSetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _setterImposter.Called(_criteria, count);
                    }

                    IIndexer_1IndexerSetterFluentBuilder IIndexer_1IndexerSetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterOutcomeBuilder
        {
            IIndexer_1IndexerGetterContinuationBuilder Returns(int value);
            IIndexer_1IndexerGetterContinuationBuilder Returns(global::System.Func<int> valueGenerator);
            IIndexer_1IndexerGetterContinuationBuilder Returns(Indexer_1IndexerDelegate valueGenerator);
            IIndexer_1IndexerGetterContinuationBuilder Throws(global::System.Exception exception);
            IIndexer_1IndexerGetterContinuationBuilder Throws<TException>()
                where TException : Exception, new();
            IIndexer_1IndexerGetterContinuationBuilder Throws(Indexer_1IndexerExceptionGenerator exceptionGenerator);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterCallbackBuilder
        {
            IIndexer_1IndexerGetterContinuationBuilder Callback(Indexer_1IndexerGetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterContinuationBuilder : IIndexer_1IndexerGetterCallbackBuilder
        {
            IIndexer_1IndexerGetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterFluentBuilder : IIndexer_1IndexerGetterOutcomeBuilder, IIndexer_1IndexerGetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerGetterBuilder : IIndexer_1IndexerGetterOutcomeBuilder, IIndexer_1IndexerGetterCallbackBuilder, IIndexer_1IndexerGetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerSetterCallbackBuilder
        {
            IIndexer_1IndexerSetterContinuationBuilder Callback(Indexer_1IndexerSetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerSetterContinuationBuilder : IIndexer_1IndexerSetterCallbackBuilder
        {
            IIndexer_1IndexerSetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerSetterFluentBuilder : IIndexer_1IndexerSetterCallbackBuilder, IIndexer_1IndexerSetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerSetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerSetterBuilder : IIndexer_1IndexerSetterCallbackBuilder, IIndexer_1IndexerSetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_1IndexerBuilder
        {
            IIndexer_1IndexerGetterBuilder Getter();
            IIndexer_1IndexerSetterBuilder Setter();
        }

        private readonly Indexer_2IndexerBuilder _Indexer_2Indexer;
        public IIndexer_2IndexerBuilder this[global::Imposter.Abstractions.Arg<T> key, global::Imposter.Abstractions.Arg<int> index] => new Indexer_2IndexerBuilder.InvocationBuilder(_Indexer_2Indexer, new Indexer_2IndexerArgumentsCriteria(key, index));
        public delegate T Indexer_2IndexerDelegate(T key, int index);
        public delegate void Indexer_2IndexerGetterCallback(T key, int index);
        public delegate void Indexer_2IndexerSetterCallback(T key, int index, T value);
        public delegate global::System.Exception Indexer_2IndexerExceptionGenerator(T key, int index);
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_2IndexerArguments : global::System.IEquatable<Indexer_2IndexerArguments>
        {
            public T key;
            public int index;
            internal Indexer_2IndexerArguments(T key, int index)
            {
                this.key = key;
                this.index = index;
            }

            public bool Equals(Indexer_2IndexerArguments? other)
            {
                if (other == null)
                {
                    return false;
                }

                return (true && (key == other.key)) && (index == other.index);
            }

            public override bool Equals(object? obj)
            {
                return obj is Indexer_2IndexerArguments other && Equals(other);
            }

            public override int GetHashCode()
            {
                global::System.HashCode hash = new global::System.HashCode();
                hash.Add(key);
                hash.Add(index);
                return hash.ToHashCode();
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_2IndexerArgumentsCriteria
        {
            public global::Imposter.Abstractions.Arg<T> key;
            public global::Imposter.Abstractions.Arg<int> index;
            internal Indexer_2IndexerArgumentsCriteria(global::Imposter.Abstractions.Arg<T> key, global::Imposter.Abstractions.Arg<int> index)
            {
                this.key = key;
                this.index = index;
            }

            public bool Matches(Indexer_2IndexerArguments arguments)
            {
                return key.Matches(arguments.key) && index.Matches(arguments.index);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class Indexer_2IndexerBuilder
        {
            private readonly DefaultIndexer_2IndexerBehaviour _Indexer_2DefaultIndexerBehaviour = new DefaultIndexer_2IndexerBehaviour();
            private readonly GetterImposter _getterImposter;
            private readonly SetterImposter _setterImposter;
            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultIndexer_2IndexerBehaviour
            {
                private bool _isOn = true;
                internal bool IsOn
                {
                    get
                    {
                        return global::System.Threading.Volatile.Read(ref _isOn);
                    }

                    set
                    {
                        global::System.Threading.Volatile.Write(ref _isOn, value);
                    }
                }

                internal global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_2IndexerArguments, T> BackingField = new global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_2IndexerArguments, T>();
                internal T Get(Indexer_2IndexerArguments arguments, global::System.Func<T>? baseImplementation = null)
                {
                    T value = default(T);
                    if (BackingField.TryGetValue(arguments, out value))
                        return value;
                    if (baseImplementation != null)
                        return baseImplementation();
                    return default(T);
                }

                internal void Set(Indexer_2IndexerArguments arguments, T value, global::System.Action? baseImplementation = null)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                        return;
                    }

                    BackingField[arguments] = value;
                }
            }

            internal Indexer_2IndexerBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
            {
                this._getterImposter = new GetterImposter(_Indexer_2DefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
                this._setterImposter = new SetterImposter(_Indexer_2DefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
            }

            internal IIndexer_2IndexerGetterBuilder CreateGetter(Indexer_2IndexerArgumentsCriteria criteria)
            {
                return new GetterImposter.Builder(_getterImposter, criteria);
            }

            internal IIndexer_2IndexerSetterBuilder CreateSetter(Indexer_2IndexerArgumentsCriteria criteria)
            {
                _setterImposter.MarkConfigured();
                return new SetterImposter.Builder(_setterImposter, criteria);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class InvocationBuilder : IIndexer_2IndexerBuilder
            {
                private readonly Indexer_2IndexerBuilder _builder;
                private readonly Indexer_2IndexerArgumentsCriteria _criteria;
                internal InvocationBuilder(Indexer_2IndexerBuilder builder, Indexer_2IndexerArgumentsCriteria criteria)
                {
                    this._builder = builder;
                    this._criteria = criteria;
                }

                public IIndexer_2IndexerGetterBuilder Getter()
                {
                    return _builder.CreateGetter(_criteria);
                }

                public IIndexer_2IndexerSetterBuilder Setter()
                {
                    return _builder.CreateSetter(_criteria);
                }
            }

            internal T Get(T key, int index)
            {
                return _getterImposter.Get(key, index);
            }

            internal void Set(T key, int index, T value)
            {
                _setterImposter.Set(key, index, value, null);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class GetterImposter
            {
                private readonly DefaultIndexer_2IndexerBehaviour _defaultBehaviour;
                private readonly global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter> _getterInvocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_2IndexerArgumentsCriteria, GetterInvocationImposter> _setupLookup = new global::System.Collections.Concurrent.ConcurrentDictionary<Indexer_2IndexerArgumentsCriteria, GetterInvocationImposter>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<Indexer_2IndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<Indexer_2IndexerArguments>();
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredReturn;
                internal GetterImposter(DefaultIndexer_2IndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                internal T Get(T key, int index, global::System.Func<T>? baseImplementation = null)
                {
                    Indexer_2IndexerArguments arguments = new Indexer_2IndexerArguments(key, index);
                    try
                    {
                        var getterInvocationImposter = FindGetterInvocationImposter(arguments);
                        if (getterInvocationImposter is null)
                        {
                            EnsureGetterConfigured();
                            if (_defaultBehaviour.IsOn)
                                return _defaultBehaviour.Get(arguments, baseImplementation);
                            if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }
                            else
                            {
                                return default(T);
                            }
                        }

                        return getterInvocationImposter.Invoke(arguments, baseImplementation);
                    }
                    finally
                    {
                        _invocationHistory.Add(arguments);
                    }
                }

                private GetterInvocationImposter? FindGetterInvocationImposter(Indexer_2IndexerArguments arguments)
                {
                    foreach (var getterInvocationImposter in _getterInvocationImposters)
                    {
                        if (getterInvocationImposter.Criteria.Matches(arguments))
                        {
                            return getterInvocationImposter;
                        }
                    }

                    return null;
                }

                private GetterInvocationImposter GetOrCreate(Indexer_2IndexerArgumentsCriteria criteria)
                {
                    return _setupLookup.GetOrAdd(criteria, CreateSetup);
                    GetterInvocationImposter CreateSetup(Indexer_2IndexerArgumentsCriteria key)
                    {
                        GetterInvocationImposter getterInvocationImposter = new GetterInvocationImposter(this, _defaultBehaviour, key);
                        _getterInvocationImposters.Push(getterInvocationImposter);
                        return getterInvocationImposter;
                    }
                }

                private void Called(Indexer_2IndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal string PropertyDisplayName => _propertyDisplayName;

                internal void MarkReturnConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredReturn, true);
                }

                private void EnsureGetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredReturn))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexer_2IndexerGetterBuilder, IIndexer_2IndexerGetterFluentBuilder
                {
                    private readonly GetterImposter _imposter;
                    private readonly Indexer_2IndexerArgumentsCriteria _criteria;
                    internal Builder(GetterImposter _imposter, Indexer_2IndexerArgumentsCriteria _criteria)
                    {
                        this._imposter = _imposter;
                        this._criteria = _criteria;
                    }

                    private GetterInvocationImposter InvocationImposter => _imposter.GetOrCreate(_criteria);

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Returns(T value)
                    {
                        InvocationImposter.AddReturnValue(arguments => value);
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Returns(global::System.Func<T> valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator());
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Returns(Indexer_2IndexerDelegate valueGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => valueGenerator(arguments.key, arguments.index));
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Throws(global::System.Exception exception)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exception);
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Throws<TException>()
                    {
                        InvocationImposter.AddReturnValue(arguments => throw new TException());
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterOutcomeBuilder.Throws(Indexer_2IndexerExceptionGenerator exceptionGenerator)
                    {
                        InvocationImposter.AddReturnValue(arguments => throw exceptionGenerator(arguments.key, arguments.index));
                        return this;
                    }

                    IIndexer_2IndexerGetterContinuationBuilder IIndexer_2IndexerGetterCallbackBuilder.Callback(Indexer_2IndexerGetterCallback callback)
                    {
                        InvocationImposter.AddCallback(callback);
                        return this;
                    }

                    void IIndexer_2IndexerGetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _imposter.Called(_criteria, count);
                    }

                    IIndexer_2IndexerGetterFluentBuilder IIndexer_2IndexerGetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                private sealed class GetterInvocationImposter
                {
                    private readonly GetterImposter _parent;
                    private readonly DefaultIndexer_2IndexerBehaviour _defaultBehaviour;
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<Indexer_2IndexerArguments, global::System.Func<T>, T>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<Indexer_2IndexerArguments, global::System.Func<T>, T>>();
                    private readonly global::System.Collections.Concurrent.ConcurrentQueue<Indexer_2IndexerGetterCallback> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<Indexer_2IndexerGetterCallback>();
                    private volatile global::System.Func<Indexer_2IndexerArguments, global::System.Func<T>, T>? _lastReturnValue;
                    private int _invocationCount;
                    private string _propertyDisplayName;
                    internal Indexer_2IndexerArgumentsCriteria Criteria { get; private set; }
                    internal int InvocationCount => global::System.Threading.Volatile.Read(ref _invocationCount);

                    internal GetterInvocationImposter(GetterImposter parent, DefaultIndexer_2IndexerBehaviour defaultBehaviour, Indexer_2IndexerArgumentsCriteria criteria)
                    {
                        this._parent = parent;
                        this._defaultBehaviour = defaultBehaviour;
                        this._propertyDisplayName = parent.PropertyDisplayName;
                        this.Criteria = criteria;
                    }

                    internal void AddReturnValue(global::System.Func<Indexer_2IndexerArguments, T> generator)
                    {
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) => generator(arguments));
                        _parent.MarkReturnConfigured();
                    }

                    internal void AddCallback(Indexer_2IndexerGetterCallback callback)
                    {
                        _callbacks.Enqueue(callback);
                    }

                    internal T Invoke(Indexer_2IndexerArguments arguments, global::System.Func<T>? baseImplementation = null)
                    {
                        global::System.Threading.Interlocked.Increment(ref _invocationCount);
                        foreach (var callback in _callbacks)
                        {
                            callback(arguments.key, arguments.index);
                        }

                        global::System.Func<Indexer_2IndexerArguments, global::System.Func<T>, T> generator = ResolveNextGenerator(arguments);
                        return generator(arguments, baseImplementation);
                    }

                    private global::System.Func<Indexer_2IndexerArguments, global::System.Func<T>, T> ResolveNextGenerator(Indexer_2IndexerArguments arguments)
                    {
                        if (_defaultBehaviour.IsOn)
                        {
                            return (arguments, baseImplementation) => _defaultBehaviour.Get(arguments, baseImplementation);
                        }

                        _returnValues.TryDequeue(out var returnValue);
                        var nextReturnValue = returnValue ?? _lastReturnValue;
                        if (nextReturnValue == null)
                        {
                            throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                        }

                        _lastReturnValue = nextReturnValue;
                        return nextReturnValue!;
                    }

                    internal void UseBaseImplementation()
                    {
                        _parent.MarkReturnConfigured();
                        _defaultBehaviour.IsOn = false;
                        _returnValues.Enqueue((arguments, baseImplementation) =>
                        {
                            if (baseImplementation == null)
                            {
                                throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                            }

                            return baseImplementation();
                        });
                        _lastReturnValue = null;
                    }
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            private sealed class SetterImposter
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<(Indexer_2IndexerArgumentsCriteria Criteria, Indexer_2IndexerSetterCallback Callback)> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<(Indexer_2IndexerArgumentsCriteria Criteria, Indexer_2IndexerSetterCallback Callback)>();
                private readonly global::System.Collections.Concurrent.ConcurrentBag<Indexer_2IndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentBag<Indexer_2IndexerArguments>();
                private readonly DefaultIndexer_2IndexerBehaviour _defaultBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredSetter;
                internal SetterImposter(DefaultIndexer_2IndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultBehaviour = defaultBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                public void Callback(Indexer_2IndexerArgumentsCriteria criteria, Indexer_2IndexerSetterCallback callback)
                {
                    _callbacks.Enqueue((criteria, callback));
                }

                public void Called(Indexer_2IndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
                {
                    int invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount);
                    }
                }

                internal void Set(T key, int index, T value, global::System.Action? baseImplementation = null)
                {
                    EnsureSetterConfigured();
                    Indexer_2IndexerArguments arguments = new Indexer_2IndexerArguments(key, index);
                    _invocationHistory.Add(arguments);
                    bool matchedCallback = false;
                    foreach (var registration in _callbacks)
                    {
                        if (registration.Criteria.Matches(arguments))
                        {
                            registration.Callback(arguments.key, arguments.index, value);
                            matchedCallback = true;
                        }
                    }

                    if (!matchedCallback && _defaultBehaviour.IsOn)
                    {
                        _defaultBehaviour.Set(arguments, value, null);
                    }
                }

                private void EnsureSetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredSetter))
                    {
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
                    }
                }

                internal void MarkConfigured()
                {
                    global::System.Threading.Volatile.Write(ref _hasConfiguredSetter, true);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : IIndexer_2IndexerSetterBuilder, IIndexer_2IndexerSetterFluentBuilder
                {
                    private readonly SetterImposter _setterImposter;
                    private readonly Indexer_2IndexerArgumentsCriteria _criteria;
                    internal Builder(SetterImposter _setterImposter, Indexer_2IndexerArgumentsCriteria _criteria)
                    {
                        this._setterImposter = _setterImposter;
                        this._criteria = _criteria;
                    }

                    IIndexer_2IndexerSetterContinuationBuilder IIndexer_2IndexerSetterCallbackBuilder.Callback(Indexer_2IndexerSetterCallback callback)
                    {
                        _setterImposter.Callback(_criteria, callback);
                        return this;
                    }

                    void IIndexer_2IndexerSetterVerifier.Called(global::Imposter.Abstractions.Count count)
                    {
                        _setterImposter.Called(_criteria, count);
                    }

                    IIndexer_2IndexerSetterFluentBuilder IIndexer_2IndexerSetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterOutcomeBuilder
        {
            IIndexer_2IndexerGetterContinuationBuilder Returns(T value);
            IIndexer_2IndexerGetterContinuationBuilder Returns(global::System.Func<T> valueGenerator);
            IIndexer_2IndexerGetterContinuationBuilder Returns(Indexer_2IndexerDelegate valueGenerator);
            IIndexer_2IndexerGetterContinuationBuilder Throws(global::System.Exception exception);
            IIndexer_2IndexerGetterContinuationBuilder Throws<TException>()
                where TException : Exception, new();
            IIndexer_2IndexerGetterContinuationBuilder Throws(Indexer_2IndexerExceptionGenerator exceptionGenerator);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterCallbackBuilder
        {
            IIndexer_2IndexerGetterContinuationBuilder Callback(Indexer_2IndexerGetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterContinuationBuilder : IIndexer_2IndexerGetterCallbackBuilder
        {
            IIndexer_2IndexerGetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterFluentBuilder : IIndexer_2IndexerGetterOutcomeBuilder, IIndexer_2IndexerGetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerGetterBuilder : IIndexer_2IndexerGetterOutcomeBuilder, IIndexer_2IndexerGetterCallbackBuilder, IIndexer_2IndexerGetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerSetterCallbackBuilder
        {
            IIndexer_2IndexerSetterContinuationBuilder Callback(Indexer_2IndexerSetterCallback callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerSetterContinuationBuilder : IIndexer_2IndexerSetterCallbackBuilder
        {
            IIndexer_2IndexerSetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerSetterFluentBuilder : IIndexer_2IndexerSetterCallbackBuilder, IIndexer_2IndexerSetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerSetterVerifier
        {
            void Called(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerSetterBuilder : IIndexer_2IndexerSetterCallbackBuilder, IIndexer_2IndexerSetterVerifier
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IIndexer_2IndexerBuilder
        {
            IIndexer_2IndexerGetterBuilder Getter();
            IIndexer_2IndexerSetterBuilder Setter();
        }

        public IHaveIndexerImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
        {
            this._IndexerIndexer = new IndexerIndexerBuilder(invocationBehavior, "Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>.this[int index]");
            this._Indexer_1Indexer = new Indexer_1IndexerBuilder(invocationBehavior, "Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>.this[T key]");
            this._Indexer_2Indexer = new Indexer_2IndexerBuilder(invocationBehavior, "Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>.this[T key, int index]");
            this._imposterInstance = new ImposterTargetInstance(this);
            this._invocationBehavior = invocationBehavior;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        class ImposterTargetInstance : global::Imposter.Tests.Features.OpenGenericImposter.IHaveIndexer<T>
        {
            private readonly IHaveIndexerImposter<T> _imposter;
            public ImposterTargetInstance(IHaveIndexerImposter<T> _imposter)
            {
                this._imposter = _imposter;
            }

            public T this[int index]
            {
                get
                {
                    return _imposter._IndexerIndexer.Get(index);
                }

                set
                {
                    _imposter._IndexerIndexer.Set(index, value);
                }
            }

            public int this[T key]
            {
                get
                {
                    return _imposter._Indexer_1Indexer.Get(key);
                }

                set
                {
                    _imposter._Indexer_1Indexer.Set(key, value);
                }
            }

            public T this[T key, int index]
            {
                get
                {
                    return _imposter._Indexer_2Indexer.Get(key, index);
                }

                set
                {
                    _imposter._Indexer_2Indexer.Set(key, index, value);
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
