// <auto-generated />
#nullable enable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.EventImpersonation;

namespace Imposter.Tests.Features.EventImpersonation
{
	[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
	public sealed class IEventSetupSutImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.EventImpersonation.IEventSetupSut>, IEventSetupSutImposter.IEventSetupSutSetup
	{
		private ImposterTargetInstance _imposterInstance;
		global::Imposter.Tests.Features.EventImpersonation.IEventSetupSut global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.EventImpersonation.IEventSetupSut>.Instance()
		{
			return _imposterInstance;
		}

		public IAsyncSomethingHappenedEventImposterBuilder AsyncSomethingHappened => _AsyncSomethingHappened;

		private readonly AsyncSomethingHappenedEventImposterBuilder _AsyncSomethingHappened;
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IAsyncSomethingHappenedEventImposterBuilder : IAsyncSomethingHappenedEventImposterSetupBuilder, IAsyncSomethingHappenedEventImposterVerificationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IAsyncSomethingHappenedEventImposterSetupBuilder
		{
			IAsyncSomethingHappenedEventImposterSetupBuilder Callback(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> callback);
			global::System.Threading.Tasks.Task<IAsyncSomethingHappenedEventImposterSetupBuilder> RaiseAsync(object arg1, global::System.EventArgs arg2);
			IAsyncSomethingHappenedEventImposterSetupBuilder OnSubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> interceptor);
			IAsyncSomethingHappenedEventImposterSetupBuilder OnUnsubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> interceptor);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IAsyncSomethingHappenedEventImposterVerificationBuilder
		{
			IAsyncSomethingHappenedEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> criteria, global::Imposter.Abstractions.Count count);
			IAsyncSomethingHappenedEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> criteria, global::Imposter.Abstractions.Count count);
			IAsyncSomethingHappenedEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> arg1Criteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> arg2Criteria, global::Imposter.Abstractions.Count count);
			IAsyncSomethingHappenedEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> handlerCriteria, global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal sealed class AsyncSomethingHappenedEventImposterBuilder : IAsyncSomethingHappenedEventImposterBuilder, IAsyncSomethingHappenedEventImposterSetupBuilder, IAsyncSomethingHappenedEventImposterVerificationBuilder
		{
			private global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>? _activeHandlers;
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> _subscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> _unsubscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>> _subscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>> _unsubscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(object arg1, global::System.EventArgs arg2)> _history = new global::System.Collections.Concurrent.ConcurrentQueue<(object arg1, global::System.EventArgs arg2)>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> Handler, object arg1, global::System.EventArgs arg2)> _handlerInvocations = new global::System.Collections.Concurrent.ConcurrentQueue<(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> Handler, object arg1, global::System.EventArgs arg2)>();
			internal AsyncSomethingHappenedEventImposterBuilder()
			{
			}

			internal void Subscribe(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>?)global::System.Delegate.Combine(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_subscribeHistory.Enqueue(handler);
				foreach (var interceptor in _subscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			internal void Unsubscribe(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>?)global::System.Delegate.Remove(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_unsubscribeHistory.Enqueue(handler);
				foreach (var interceptor in _unsubscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			IAsyncSomethingHappenedEventImposterSetupBuilder IAsyncSomethingHappenedEventImposterSetupBuilder.Callback(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task> callback)
			{
				if (callback is null)
				{
					throw new global::System.ArgumentNullException(nameof(callback));
				}

				_callbacks.Enqueue(callback);
				return this;
			}

			async global::System.Threading.Tasks.Task<IAsyncSomethingHappenedEventImposterSetupBuilder> IAsyncSomethingHappenedEventImposterSetupBuilder.RaiseAsync(object arg1, global::System.EventArgs arg2)
			{
				await RaiseCoreAsync(arg1, arg2).ConfigureAwait(false);
				return this;
			}

			IAsyncSomethingHappenedEventImposterVerificationBuilder IAsyncSomethingHappenedEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _subscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _subscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("AsyncSomethingHappened subscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IAsyncSomethingHappenedEventImposterVerificationBuilder IAsyncSomethingHappenedEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _unsubscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _unsubscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("AsyncSomethingHappened unsubscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IAsyncSomethingHappenedEventImposterSetupBuilder IAsyncSomethingHappenedEventImposterSetupBuilder.OnSubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_subscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			IAsyncSomethingHappenedEventImposterSetupBuilder IAsyncSomethingHappenedEventImposterSetupBuilder.OnUnsubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_unsubscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			IAsyncSomethingHappenedEventImposterVerificationBuilder IAsyncSomethingHappenedEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> arg1Criteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> arg2Criteria, global::Imposter.Abstractions.Count count)
			{
				if (arg1Criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(arg1Criteria));
				}

				if (arg2Criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(arg2Criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _history.Count(entry => arg1Criteria.Matches(entry.arg1) && arg2Criteria.Matches(entry.arg2));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _history)
					{
						if (arg1Criteria.Matches(entry.arg1) && arg2Criteria.Matches(entry.arg2))
						{
							performedInvocations.Add("AsyncSomethingHappened raised" + " arg1: " + FormatValue(entry.arg1) + " arg2: " + FormatValue(entry.arg2));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IAsyncSomethingHappenedEventImposterVerificationBuilder IAsyncSomethingHappenedEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> handlerCriteria, global::Imposter.Abstractions.Count count)
			{
				if (handlerCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(handlerCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _handlerInvocations.Count(entry => handlerCriteria.Matches(entry.Handler));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _handlerInvocations)
					{
						if (handlerCriteria.Matches(entry.Handler))
						{
							performedInvocations.Add("AsyncSomethingHappened handler invoked" + " handler: " + FormatValue(entry.Handler) + " arg1: " + FormatValue(entry.arg1) + " arg2: " + FormatValue(entry.arg2));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			private async global::System.Threading.Tasks.Task RaiseCoreAsync(object arg1, global::System.EventArgs arg2)
			{
				_history.Enqueue((arg1, arg2));
				global::System.Collections.Generic.List<global::System.Threading.Tasks.Task> pendingTasks = new global::System.Collections.Generic.List<global::System.Threading.Tasks.Task>();
				foreach (var callback in _callbacks)
				{
					var task = callback(arg1, arg2);
					if (task != default)
					{
						pendingTasks.Add(task);
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}

				pendingTasks.Clear();
				foreach (var handler in EnumerateActiveHandlers())
				{
					_handlerInvocations.Enqueue((handler, arg1, arg2));
					var task = handler(arg1, arg2);
					if (task != default)
					{
						pendingTasks.Add(task);
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}
			}

			private global::System.Collections.Generic.IEnumerable<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>> EnumerateActiveHandlers()
			{
				var handlers = _activeHandlers;
				if (handlers != null)
				{
					foreach (var handler in handlers.GetInvocationList())
					{
						yield return (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.Task>)handler;
					}
				}
			}

			private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, global::System.Func<string> performedInvocationsFactory)
			{
				if (!expected.Matches(actual))
				{
					throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual, performedInvocationsFactory());
				}
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		public ICustomAsyncSomethingHappenedEventImposterBuilder CustomAsyncSomethingHappened => _CustomAsyncSomethingHappened;

		private readonly CustomAsyncSomethingHappenedEventImposterBuilder _CustomAsyncSomethingHappened;
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ICustomAsyncSomethingHappenedEventImposterBuilder : ICustomAsyncSomethingHappenedEventImposterSetupBuilder, ICustomAsyncSomethingHappenedEventImposterVerificationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ICustomAsyncSomethingHappenedEventImposterSetupBuilder
		{
			ICustomAsyncSomethingHappenedEventImposterSetupBuilder Callback(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> callback);
			global::System.Threading.Tasks.Task<ICustomAsyncSomethingHappenedEventImposterSetupBuilder> RaiseAsync(object sender, global::System.EventArgs args);
			ICustomAsyncSomethingHappenedEventImposterSetupBuilder OnSubscribe(global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> interceptor);
			ICustomAsyncSomethingHappenedEventImposterSetupBuilder OnUnsubscribe(global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> interceptor);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ICustomAsyncSomethingHappenedEventImposterVerificationBuilder
		{
			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> criteria, global::Imposter.Abstractions.Count count);
			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> criteria, global::Imposter.Abstractions.Count count);
			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> argsCriteria, global::Imposter.Abstractions.Count count);
			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> handlerCriteria, global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal sealed class CustomAsyncSomethingHappenedEventImposterBuilder : ICustomAsyncSomethingHappenedEventImposterBuilder, ICustomAsyncSomethingHappenedEventImposterSetupBuilder, ICustomAsyncSomethingHappenedEventImposterVerificationBuilder
		{
			private global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>? _activeHandlers;
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> _subscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> _unsubscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>> _subscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>> _unsubscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs args)> _history = new global::System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs args)>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> Handler, object sender, global::System.EventArgs args)> _handlerInvocations = new global::System.Collections.Concurrent.ConcurrentQueue<(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> Handler, object sender, global::System.EventArgs args)>();
			internal CustomAsyncSomethingHappenedEventImposterBuilder()
			{
			}

			internal void Subscribe(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>?)global::System.Delegate.Combine(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_subscribeHistory.Enqueue(handler);
				foreach (var interceptor in _subscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			internal void Unsubscribe(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>?)global::System.Delegate.Remove(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_unsubscribeHistory.Enqueue(handler);
				foreach (var interceptor in _unsubscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			ICustomAsyncSomethingHappenedEventImposterSetupBuilder ICustomAsyncSomethingHappenedEventImposterSetupBuilder.Callback(global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs> callback)
			{
				if (callback is null)
				{
					throw new global::System.ArgumentNullException(nameof(callback));
				}

				_callbacks.Enqueue(callback);
				return this;
			}

			async global::System.Threading.Tasks.Task<ICustomAsyncSomethingHappenedEventImposterSetupBuilder> ICustomAsyncSomethingHappenedEventImposterSetupBuilder.RaiseAsync(object sender, global::System.EventArgs args)
			{
				await RaiseCoreAsync(sender, args).ConfigureAwait(false);
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder ICustomAsyncSomethingHappenedEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _subscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _subscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("CustomAsyncSomethingHappened subscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder ICustomAsyncSomethingHappenedEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _unsubscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _unsubscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("CustomAsyncSomethingHappened unsubscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterSetupBuilder ICustomAsyncSomethingHappenedEventImposterSetupBuilder.OnSubscribe(global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_subscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterSetupBuilder ICustomAsyncSomethingHappenedEventImposterSetupBuilder.OnUnsubscribe(global::System.Action<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_unsubscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder ICustomAsyncSomethingHappenedEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> argsCriteria, global::Imposter.Abstractions.Count count)
			{
				if (senderCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(senderCriteria));
				}

				if (argsCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(argsCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _history.Count(entry => senderCriteria.Matches(entry.sender) && argsCriteria.Matches(entry.args));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _history)
					{
						if (senderCriteria.Matches(entry.sender) && argsCriteria.Matches(entry.args))
						{
							performedInvocations.Add("CustomAsyncSomethingHappened raised" + " sender: " + FormatValue(entry.sender) + " args: " + FormatValue(entry.args));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ICustomAsyncSomethingHappenedEventImposterVerificationBuilder ICustomAsyncSomethingHappenedEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> handlerCriteria, global::Imposter.Abstractions.Count count)
			{
				if (handlerCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(handlerCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _handlerInvocations.Count(entry => handlerCriteria.Matches(entry.Handler));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _handlerInvocations)
					{
						if (handlerCriteria.Matches(entry.Handler))
						{
							performedInvocations.Add("CustomAsyncSomethingHappened handler invoked" + " handler: " + FormatValue(entry.Handler) + " sender: " + FormatValue(entry.sender) + " args: " + FormatValue(entry.args));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			private async global::System.Threading.Tasks.Task RaiseCoreAsync(object sender, global::System.EventArgs args)
			{
				_history.Enqueue((sender, args));
				global::System.Collections.Generic.List<global::System.Threading.Tasks.Task> pendingTasks = new global::System.Collections.Generic.List<global::System.Threading.Tasks.Task>();
				foreach (var callback in _callbacks)
				{
					var task = callback(sender, args);
					if (task != default)
					{
						pendingTasks.Add(task);
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}

				pendingTasks.Clear();
				foreach (var handler in EnumerateActiveHandlers())
				{
					_handlerInvocations.Enqueue((handler, sender, args));
					var task = handler(sender, args);
					if (task != default)
					{
						pendingTasks.Add(task);
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}
			}

			private global::System.Collections.Generic.IEnumerable<global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>> EnumerateActiveHandlers()
			{
				var handlers = _activeHandlers;
				if (handlers != null)
				{
					foreach (var handler in handlers.GetInvocationList())
					{
						yield return (global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>)handler;
					}
				}
			}

			private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, global::System.Func<string> performedInvocationsFactory)
			{
				if (!expected.Matches(actual))
				{
					throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual, performedInvocationsFactory());
				}
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		public ISomethingHappenedEventImposterBuilder SomethingHappened => _SomethingHappened;

		private readonly SomethingHappenedEventImposterBuilder _SomethingHappened;
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ISomethingHappenedEventImposterBuilder : ISomethingHappenedEventImposterSetupBuilder, ISomethingHappenedEventImposterVerificationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ISomethingHappenedEventImposterSetupBuilder
		{
			ISomethingHappenedEventImposterSetupBuilder Callback(global::System.EventHandler callback);
			ISomethingHappenedEventImposterSetupBuilder Raise(object sender, global::System.EventArgs e);
			ISomethingHappenedEventImposterSetupBuilder OnSubscribe(global::System.Action<global::System.EventHandler> interceptor);
			ISomethingHappenedEventImposterSetupBuilder OnUnsubscribe(global::System.Action<global::System.EventHandler> interceptor);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ISomethingHappenedEventImposterVerificationBuilder
		{
			ISomethingHappenedEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
			ISomethingHappenedEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
			ISomethingHappenedEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count);
			ISomethingHappenedEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal sealed class SomethingHappenedEventImposterBuilder : ISomethingHappenedEventImposterBuilder, ISomethingHappenedEventImposterSetupBuilder, ISomethingHappenedEventImposterVerificationBuilder
		{
			private global::System.EventHandler? _activeHandlers;
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _subscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _unsubscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.EventHandler>> _subscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.EventHandler>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.EventHandler>> _unsubscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.EventHandler>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)> _history = new global::System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)> _handlerInvocations = new global::System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)>();
			internal SomethingHappenedEventImposterBuilder()
			{
			}

			internal void Subscribe(global::System.EventHandler handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.EventHandler?)global::System.Delegate.Combine(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_subscribeHistory.Enqueue(handler);
				foreach (var interceptor in _subscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			internal void Unsubscribe(global::System.EventHandler handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.EventHandler?)global::System.Delegate.Remove(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_unsubscribeHistory.Enqueue(handler);
				foreach (var interceptor in _unsubscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			ISomethingHappenedEventImposterSetupBuilder ISomethingHappenedEventImposterSetupBuilder.Callback(global::System.EventHandler callback)
			{
				if (callback is null)
				{
					throw new global::System.ArgumentNullException(nameof(callback));
				}

				_callbacks.Enqueue(callback);
				return this;
			}

			ISomethingHappenedEventImposterSetupBuilder ISomethingHappenedEventImposterSetupBuilder.Raise(object sender, global::System.EventArgs e)
			{
				RaiseInternal(sender, e);
				return this;
			}

			ISomethingHappenedEventImposterVerificationBuilder ISomethingHappenedEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _subscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _subscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("SomethingHappened subscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ISomethingHappenedEventImposterVerificationBuilder ISomethingHappenedEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _unsubscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _unsubscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("SomethingHappened unsubscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ISomethingHappenedEventImposterSetupBuilder ISomethingHappenedEventImposterSetupBuilder.OnSubscribe(global::System.Action<global::System.EventHandler> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_subscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			ISomethingHappenedEventImposterSetupBuilder ISomethingHappenedEventImposterSetupBuilder.OnUnsubscribe(global::System.Action<global::System.EventHandler> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_unsubscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			ISomethingHappenedEventImposterVerificationBuilder ISomethingHappenedEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count)
			{
				if (senderCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(senderCriteria));
				}

				if (eCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(eCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _history.Count(entry => senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _history)
					{
						if (senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e))
						{
							performedInvocations.Add("SomethingHappened raised" + " sender: " + FormatValue(entry.sender) + " e: " + FormatValue(entry.e));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			ISomethingHappenedEventImposterVerificationBuilder ISomethingHappenedEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count)
			{
				if (handlerCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(handlerCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _handlerInvocations.Count(entry => handlerCriteria.Matches(entry.Handler));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _handlerInvocations)
					{
						if (handlerCriteria.Matches(entry.Handler))
						{
							performedInvocations.Add("SomethingHappened handler invoked" + " handler: " + FormatValue(entry.Handler) + " sender: " + FormatValue(entry.sender) + " e: " + FormatValue(entry.e));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			private void RaiseInternal(object sender, global::System.EventArgs e)
			{
				_history.Enqueue((sender, e));
				foreach (var callback in _callbacks)
				{
					callback(sender, e);
				}

				foreach (var handler in EnumerateActiveHandlers())
				{
					_handlerInvocations.Enqueue((handler, sender, e));
					handler(sender, e);
				}
			}

			private global::System.Collections.Generic.IEnumerable<global::System.EventHandler> EnumerateActiveHandlers()
			{
				var handlers = _activeHandlers;
				if (handlers != null)
				{
					foreach (var handler in handlers.GetInvocationList())
					{
						yield return (global::System.EventHandler)handler;
					}
				}
			}

			private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, global::System.Func<string> performedInvocationsFactory)
			{
				if (!expected.Matches(actual))
				{
					throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual, performedInvocationsFactory());
				}
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		public IValueTaskSomethingHappenedEventImposterBuilder ValueTaskSomethingHappened => _ValueTaskSomethingHappened;

		private readonly ValueTaskSomethingHappenedEventImposterBuilder _ValueTaskSomethingHappened;
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IValueTaskSomethingHappenedEventImposterBuilder : IValueTaskSomethingHappenedEventImposterSetupBuilder, IValueTaskSomethingHappenedEventImposterVerificationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IValueTaskSomethingHappenedEventImposterSetupBuilder
		{
			IValueTaskSomethingHappenedEventImposterSetupBuilder Callback(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> callback);
			global::System.Threading.Tasks.Task<IValueTaskSomethingHappenedEventImposterSetupBuilder> RaiseAsync(object arg1, global::System.EventArgs arg2);
			IValueTaskSomethingHappenedEventImposterSetupBuilder OnSubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> interceptor);
			IValueTaskSomethingHappenedEventImposterSetupBuilder OnUnsubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> interceptor);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IValueTaskSomethingHappenedEventImposterVerificationBuilder
		{
			IValueTaskSomethingHappenedEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> criteria, global::Imposter.Abstractions.Count count);
			IValueTaskSomethingHappenedEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> criteria, global::Imposter.Abstractions.Count count);
			IValueTaskSomethingHappenedEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> arg1Criteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> arg2Criteria, global::Imposter.Abstractions.Count count);
			IValueTaskSomethingHappenedEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> handlerCriteria, global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal sealed class ValueTaskSomethingHappenedEventImposterBuilder : IValueTaskSomethingHappenedEventImposterBuilder, IValueTaskSomethingHappenedEventImposterSetupBuilder, IValueTaskSomethingHappenedEventImposterVerificationBuilder
		{
			private global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>? _activeHandlers;
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> _subscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> _unsubscribeHistory = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>> _subscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>> _unsubscribeInterceptors = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(object arg1, global::System.EventArgs arg2)> _history = new global::System.Collections.Concurrent.ConcurrentQueue<(object arg1, global::System.EventArgs arg2)>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> Handler, object arg1, global::System.EventArgs arg2)> _handlerInvocations = new global::System.Collections.Concurrent.ConcurrentQueue<(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> Handler, object arg1, global::System.EventArgs arg2)>();
			internal ValueTaskSomethingHappenedEventImposterBuilder()
			{
			}

			internal void Subscribe(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>?)global::System.Delegate.Combine(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_subscribeHistory.Enqueue(handler);
				foreach (var interceptor in _subscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			internal void Unsubscribe(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> handler)
			{
				if (handler is null)
				{
					throw new global::System.ArgumentNullException(nameof(handler));
				}

				var handlers = _activeHandlers;
				while (true)
				{
					var updated = (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>?)global::System.Delegate.Remove(handlers, handler);
					var observed = global::System.Threading.Interlocked.CompareExchange(ref _activeHandlers, updated, handlers);
					if (object.ReferenceEquals(observed, handlers))
					{
						break;
					}

					handlers = observed;
				}

				_unsubscribeHistory.Enqueue(handler);
				foreach (var interceptor in _unsubscribeInterceptors)
				{
					interceptor(handler);
				}
			}

			IValueTaskSomethingHappenedEventImposterSetupBuilder IValueTaskSomethingHappenedEventImposterSetupBuilder.Callback(global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask> callback)
			{
				if (callback is null)
				{
					throw new global::System.ArgumentNullException(nameof(callback));
				}

				_callbacks.Enqueue(callback);
				return this;
			}

			async global::System.Threading.Tasks.Task<IValueTaskSomethingHappenedEventImposterSetupBuilder> IValueTaskSomethingHappenedEventImposterSetupBuilder.RaiseAsync(object arg1, global::System.EventArgs arg2)
			{
				await RaiseCoreAsync(arg1, arg2).ConfigureAwait(false);
				return this;
			}

			IValueTaskSomethingHappenedEventImposterVerificationBuilder IValueTaskSomethingHappenedEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _subscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _subscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("ValueTaskSomethingHappened subscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IValueTaskSomethingHappenedEventImposterVerificationBuilder IValueTaskSomethingHappenedEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> criteria, global::Imposter.Abstractions.Count count)
			{
				if (criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _unsubscribeHistory.Count(entry => criteria.Matches(entry));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _unsubscribeHistory)
					{
						if (criteria.Matches(entry))
						{
							performedInvocations.Add("ValueTaskSomethingHappened unsubscribed" + " handler: " + FormatValue(entry));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IValueTaskSomethingHappenedEventImposterSetupBuilder IValueTaskSomethingHappenedEventImposterSetupBuilder.OnSubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_subscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			IValueTaskSomethingHappenedEventImposterSetupBuilder IValueTaskSomethingHappenedEventImposterSetupBuilder.OnUnsubscribe(global::System.Action<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> interceptor)
			{
				if (interceptor is null)
				{
					throw new global::System.ArgumentNullException(nameof(interceptor));
				}

				_unsubscribeInterceptors.Enqueue(interceptor);
				return this;
			}

			IValueTaskSomethingHappenedEventImposterVerificationBuilder IValueTaskSomethingHappenedEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> arg1Criteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> arg2Criteria, global::Imposter.Abstractions.Count count)
			{
				if (arg1Criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(arg1Criteria));
				}

				if (arg2Criteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(arg2Criteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _history.Count(entry => arg1Criteria.Matches(entry.arg1) && arg2Criteria.Matches(entry.arg2));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _history)
					{
						if (arg1Criteria.Matches(entry.arg1) && arg2Criteria.Matches(entry.arg2))
						{
							performedInvocations.Add("ValueTaskSomethingHappened raised" + " arg1: " + FormatValue(entry.arg1) + " arg2: " + FormatValue(entry.arg2));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			IValueTaskSomethingHappenedEventImposterVerificationBuilder IValueTaskSomethingHappenedEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> handlerCriteria, global::Imposter.Abstractions.Count count)
			{
				if (handlerCriteria is null)
				{
					throw new global::System.ArgumentNullException(nameof(handlerCriteria));
				}

				if (count is null)
				{
					throw new global::System.ArgumentNullException(nameof(count));
				}

				int actual = _handlerInvocations.Count(entry => handlerCriteria.Matches(entry.Handler));
				EnsureCountMatches(actual, count, () =>
				{
					var performedInvocations = new global::System.Collections.Generic.List<string>();
					foreach (var entry in _handlerInvocations)
					{
						if (handlerCriteria.Matches(entry.Handler))
						{
							performedInvocations.Add("ValueTaskSomethingHappened handler invoked" + " handler: " + FormatValue(entry.Handler) + " arg1: " + FormatValue(entry.arg1) + " arg2: " + FormatValue(entry.arg2));
						}
					}

					return string.Join(global::System.Environment.NewLine, performedInvocations);
				});
				return this;
			}

			private async global::System.Threading.Tasks.Task RaiseCoreAsync(object arg1, global::System.EventArgs arg2)
			{
				_history.Enqueue((arg1, arg2));
				global::System.Collections.Generic.List<global::System.Threading.Tasks.Task> pendingTasks = new global::System.Collections.Generic.List<global::System.Threading.Tasks.Task>();
				foreach (var callback in _callbacks)
				{
					var task = callback(arg1, arg2);
					if (task != default)
					{
						pendingTasks.Add(task.AsTask());
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}

				pendingTasks.Clear();
				foreach (var handler in EnumerateActiveHandlers())
				{
					_handlerInvocations.Enqueue((handler, arg1, arg2));
					var task = handler(arg1, arg2);
					if (task != default)
					{
						pendingTasks.Add(task.AsTask());
					}
				}

				if (pendingTasks.Count > 0)
				{
					await global::System.Threading.Tasks.Task.WhenAll(pendingTasks).ConfigureAwait(false);
				}
			}

			private global::System.Collections.Generic.IEnumerable<global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>> EnumerateActiveHandlers()
			{
				var handlers = _activeHandlers;
				if (handlers != null)
				{
					foreach (var handler in handlers.GetInvocationList())
					{
						yield return (global::System.Func<object, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>)handler;
					}
				}
			}

			private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, global::System.Func<string> performedInvocationsFactory)
			{
				if (!expected.Matches(actual))
				{
					throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual, performedInvocationsFactory());
				}
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IEventSetupSutSetup
		{
			IAsyncSomethingHappenedEventImposterBuilder AsyncSomethingHappened { get; }

			ICustomAsyncSomethingHappenedEventImposterBuilder CustomAsyncSomethingHappened { get; }

			ISomethingHappenedEventImposterBuilder SomethingHappened { get; }

			IValueTaskSomethingHappenedEventImposterBuilder ValueTaskSomethingHappened { get; }
		}

		IAsyncSomethingHappenedEventImposterBuilder IEventSetupSutSetup.AsyncSomethingHappened => this.AsyncSomethingHappened;

		ICustomAsyncSomethingHappenedEventImposterBuilder IEventSetupSutSetup.CustomAsyncSomethingHappened => this.CustomAsyncSomethingHappened;

		ISomethingHappenedEventImposterBuilder IEventSetupSutSetup.SomethingHappened => this.SomethingHappened;

		IValueTaskSomethingHappenedEventImposterBuilder IEventSetupSutSetup.ValueTaskSomethingHappened => this.ValueTaskSomethingHappened;

		public IEventSetupSutSetup For(global::Imposter.Tests.Features.EventImpersonation.IEventSetupSut? interfaceType)
		{
			return this;
		}

		public IEventSetupSutImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
		{
			this._AsyncSomethingHappened = new AsyncSomethingHappenedEventImposterBuilder();
			this._CustomAsyncSomethingHappened = new CustomAsyncSomethingHappenedEventImposterBuilder();
			this._SomethingHappened = new SomethingHappenedEventImposterBuilder();
			this._ValueTaskSomethingHappened = new ValueTaskSomethingHappenedEventImposterBuilder();
			this._imposterInstance = new ImposterTargetInstance(this);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class ImposterTargetInstance : global::Imposter.Tests.Features.EventImpersonation.IEventSetupSut
		{
			private readonly IEventSetupSutImposter _imposter;
			public ImposterTargetInstance(IEventSetupSutImposter _imposter)
			{
				this._imposter = _imposter;
			}

			public event global::System.Func<object?, global::System.EventArgs, global::System.Threading.Tasks.Task>? AsyncSomethingHappened
			{
				add
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._AsyncSomethingHappened.Subscribe(value);
				}

				remove
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._AsyncSomethingHappened.Unsubscribe(value);
				}
			}

			public event global::Imposter.Tests.Features.EventImpersonation.AsyncEventHandler<global::System.EventArgs>? CustomAsyncSomethingHappened
			{
				add
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._CustomAsyncSomethingHappened.Subscribe(value);
				}

				remove
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._CustomAsyncSomethingHappened.Unsubscribe(value);
				}
			}

			public event global::System.EventHandler SomethingHappened
			{
				add
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._SomethingHappened.Subscribe(value);
				}

				remove
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._SomethingHappened.Unsubscribe(value);
				}
			}

			public event global::System.Func<object?, global::System.EventArgs, global::System.Threading.Tasks.ValueTask>? ValueTaskSomethingHappened
			{
				add
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._ValueTaskSomethingHappened.Subscribe(value);
				}

				remove
				{
					if (value is null)
					{
						throw new global::System.ArgumentNullException(nameof(value));
					}

					_imposter._ValueTaskSomethingHappened.Unsubscribe(value);
				}
			}
		}
	}
}
#nullable restore
