// <auto-generated />
#nullable enable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.ClassImpersonation.Suts;

namespace Imposter.Tests.Features.ClassImpersonation.Suts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
    public sealed class ClassWithNonVirtualAndSealedMembersImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembers>
    {
        private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
        private ImposterTargetInstance _imposterInstance;
        global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembers global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembers>.Instance()
        {
            return _imposterInstance;
        }

        public ClassWithNonVirtualAndSealedMembersImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
        {
            this._imposterInstance = new ImposterTargetInstance(this);
            this._invocationBehavior = invocationBehavior;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        class ImposterTargetInstance : global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembers
        {
            private readonly ClassWithNonVirtualAndSealedMembersImposter _imposter;
            internal ImposterTargetInstance(ClassWithNonVirtualAndSealedMembersImposter _imposter) : base()
            {
                this._imposter = _imposter;
            }
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
    public static class ClassWithNonVirtualAndSealedMembersImposterExtensions
    {
        extension(global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembers imposter)
        {
            public static global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembersImposter Imposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit) => new global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithNonVirtualAndSealedMembersImposter(invocationBehavior);
        }
    }
}
#nullable restore
