// <auto-generated />
#nullable enable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.ClassImpersonation.Suts;

namespace Imposter.Tests.Features.ClassImpersonation.Suts
{
	[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
	public sealed class ClassWithUninferableGenericMethodsImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethods>
	{
		private readonly DescribeMethodImposterCollection _describeMethodImposterCollection;
		private readonly ConvertMethodImposterCollection _convertMethodImposterCollection;
		private readonly ExecuteMethodImposterCollection _executeMethodImposterCollection;
		private readonly DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection = new DescribeMethodInvocationHistoryCollection();
		private readonly ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection = new ConvertMethodInvocationHistoryCollection();
		private readonly ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection = new ExecuteMethodInvocationHistoryCollection();
		public IDescribeMethodImposterBuilder<T> Describe<T>()
		{
			return new DescribeMethodImposter<T>.Builder(_describeMethodImposterCollection, _describeMethodInvocationHistoryCollection);
		}

		public IConvertMethodImposterBuilder<TInput, TResult> Convert<TInput, TResult>(global::Imposter.Abstractions.Arg<TInput> input)
		{
			return new ConvertMethodImposter<TInput, TResult>.Builder(_convertMethodImposterCollection, _convertMethodInvocationHistoryCollection, new ConvertArgumentsCriteria<TInput, TResult>(input));
		}

		public IExecuteMethodImposterBuilder<T> Execute<T>()
		{
			return new ExecuteMethodImposter<T>.Builder(_executeMethodImposterCollection, _executeMethodInvocationHistoryCollection);
		}

		private ImposterTargetInstance _imposterInstance;
		global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethods global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethods>.Instance()
		{
			return _imposterInstance;
		}

		public delegate string ConvertDelegate<TInput, TResult>(TInput input);
		public delegate void ConvertCallbackDelegate<TInput, TResult>(TInput input);
		public delegate global::System.Exception ConvertExceptionGeneratorDelegate<TInput, TResult>(TInput input);
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public class ConvertArguments<TInput, TResult>
		{
			public TInput input;
			internal ConvertArguments(TInput input)
			{
				this.input = input;
			}

			public ConvertArguments<TInputTarget, TResultTarget> As<TInputTarget, TResultTarget>()
			{
				return new ConvertArguments<TInputTarget, TResultTarget>(global::Imposter.Abstractions.TypeCaster.Cast<TInput, TInputTarget>(input));
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public class ConvertArgumentsCriteria<TInput, TResult>
		{
			public global::Imposter.Abstractions.Arg<TInput> input { get; }

			public ConvertArgumentsCriteria(global::Imposter.Abstractions.Arg<TInput> input)
			{
				this.input = input;
			}

			public bool Matches(ConvertArguments<TInput, TResult> arguments)
			{
				return input.Matches(arguments.input);
			}

			public ConvertArgumentsCriteria<TInputTarget, TResultTarget> As<TInputTarget, TResultTarget>()
			{
				return new ConvertArgumentsCriteria<TInputTarget, TResultTarget>(global::Imposter.Abstractions.Arg<TInputTarget>.Is(it => global::Imposter.Abstractions.TypeCaster.TryCast<TInputTarget, TInput>(it, out TInput inputTarget) && input.Matches(inputTarget)));
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IConvertMethodInvocationHistory
		{
			bool Matches<TInputTarget, TResultTarget>(ConvertArgumentsCriteria<TInputTarget, TResultTarget> criteria);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ConvertMethodInvocationHistory<TInput, TResult> : IConvertMethodInvocationHistory
		{
			internal ConvertArguments<TInput, TResult> Arguments;
			internal string? Result;
			internal global::System.Exception? Exception;
			public ConvertMethodInvocationHistory(ConvertArguments<TInput, TResult> Arguments, string? Result, global::System.Exception? Exception)
			{
				this.Arguments = Arguments;
				this.Result = Result;
				this.Exception = Exception;
			}

			public bool Matches<TInputTarget, TResultTarget>(ConvertArgumentsCriteria<TInputTarget, TResultTarget> criteria)
			{
				return ((typeof(TInputTarget) == typeof(TInput)) && (typeof(string) == typeof(string))) && criteria.As<TInput, TResult>().Matches(Arguments);
			}

			public override string ToString()
			{
				return "Convert(" + global::System.String.Join(", ", new[] { "input: " + FormatValue(Arguments.input) }) + ")" + " => " + FormatValue(Result) + (Exception == null ? "" : " threw " + FormatValue(Exception));
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ConvertMethodInvocationHistoryCollection
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<IConvertMethodInvocationHistory> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<IConvertMethodInvocationHistory>();
			internal void Add(IConvertMethodInvocationHistory invocationHistory)
			{
				_invocationHistory.Push(invocationHistory);
			}

			internal int Count<TInput, TResult>(ConvertArgumentsCriteria<TInput, TResult> argumentsCriteria)
			{
				return _invocationHistory.Count(it => it.Matches<TInput, TResult>(argumentsCriteria));
			}

			public override string ToString()
			{
				return string.Join(global::System.Environment.NewLine, _invocationHistory.Select(invocation => invocation.ToString()));
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ConvertMethodImposterCollection
		{
			private readonly ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public ConvertMethodImposterCollection(ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._convertMethodInvocationHistoryCollection = _convertMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			private readonly global::System.Collections.Concurrent.ConcurrentStack<IConvertMethodImposter> _imposters = new global::System.Collections.Concurrent.ConcurrentStack<IConvertMethodImposter>();
			internal ConvertMethodImposter<TInput, TResult> AddNew<TInput, TResult>()
			{
				var imposter = new ConvertMethodImposter<TInput, TResult>(_convertMethodInvocationHistoryCollection, _invocationBehavior);
				_imposters.Push(imposter);
				return imposter;
			}

			internal IConvertMethodImposter<TInput, TResult> GetImposterWithMatchingInvocationImposterGroup<TInput, TResult>(ConvertArguments<TInput, TResult> arguments)
			{
				foreach (var storedImposter in _imposters)
				{
					var typedImposter = storedImposter.As<TInput, TResult>();
					if ((typedImposter != null) && typedImposter.HasMatchingInvocationImposterGroup(arguments))
						return typedImposter;
				}

				return new ConvertMethodImposter<TInput, TResult>(_convertMethodInvocationHistoryCollection, _invocationBehavior);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class ConvertMethodInvocationImposterGroup<TInput, TResult>
		{
			internal static ConvertMethodInvocationImposterGroup<TInput, TResult> Default = new ConvertMethodInvocationImposterGroup<TInput, TResult>(new ConvertArgumentsCriteria<TInput, TResult>(global::Imposter.Abstractions.Arg<TInput>.Any()));
			internal ConvertArgumentsCriteria<TInput, TResult> ArgumentsCriteria { get; }

			private readonly global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter>();
			private MethodInvocationImposter? _lastestInvocationImposter;
			public ConvertMethodInvocationImposterGroup(ConvertArgumentsCriteria<TInput, TResult> argumentsCriteria)
			{
				ArgumentsCriteria = argumentsCriteria;
			}

			internal MethodInvocationImposter AddInvocationImposter()
			{
				MethodInvocationImposter invocationImposter = new MethodInvocationImposter();
				_invocationImposters.Enqueue(invocationImposter);
				return invocationImposter;
			}

			private MethodInvocationImposter? GetInvocationImposter()
			{
				if (_invocationImposters.TryDequeue(out var invocationImposter))
				{
					if (!invocationImposter.IsEmpty)
					{
						_lastestInvocationImposter = invocationImposter;
					}

					return invocationImposter;
				}

				return _lastestInvocationImposter;
			}

			public string Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, TInput input, ConvertDelegate<TInput, TResult>? baseImplementation = null)
			{
				var invocationImposter = GetInvocationImposter();
				if (invocationImposter == null)
				{
					if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					invocationImposter = MethodInvocationImposter.Default;
				}

				return invocationImposter.Invoke(invocationBehavior, methodDisplayName, input, baseImplementation);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class MethodInvocationImposter
			{
				internal static MethodInvocationImposter Default;
				static MethodInvocationImposter()
				{
					Default = new MethodInvocationImposter();
					Default.Returns(DefaultResultGenerator);
				}

				private ConvertDelegate<TInput, TResult>? _resultGenerator;
				private readonly global::System.Collections.Concurrent.ConcurrentQueue<ConvertCallbackDelegate<TInput, TResult>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<ConvertCallbackDelegate<TInput, TResult>>();
				private bool _useBaseImplementation;
				internal bool IsEmpty => !_useBaseImplementation && ((_resultGenerator == null) && (_callbacks.Count == 0));

				public string Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, TInput input, ConvertDelegate<TInput, TResult>? baseImplementation = null)
				{
					if (_useBaseImplementation)
					{
						_resultGenerator = baseImplementation ?? throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					if (_resultGenerator == null)
					{
						if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
						{
							throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
						}

						_resultGenerator = DefaultResultGenerator;
					}

					string result = _resultGenerator.Invoke(input);
					foreach (var callback in _callbacks)
					{
						callback(input);
					}

					return result;
				}

				internal void Callback(ConvertCallbackDelegate<TInput, TResult> callback)
				{
					_callbacks.Enqueue(callback);
				}

				internal void Returns(ConvertDelegate<TInput, TResult> resultGenerator)
				{
					_useBaseImplementation = false;
					_resultGenerator = resultGenerator;
				}

				internal void Returns(string value)
				{
					_useBaseImplementation = false;
					_resultGenerator = (TInput input) =>
					{
						return value;
					};
				}

				internal void Throws(ConvertExceptionGeneratorDelegate<TInput, TResult> exceptionGenerator)
				{
					_useBaseImplementation = false;
					_resultGenerator = (TInput input) =>
					{
						throw exceptionGenerator(input);
					};
				}

				internal void UseBaseImplementation()
				{
					_useBaseImplementation = true;
					_resultGenerator = null;
				}

				internal static string DefaultResultGenerator(TInput input)
				{
					return default !;
				}
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IConvertMethodInvocationImposterGroupCallback<TInput, TResult>
		{
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Callback(ConvertCallbackDelegate<TInput, TResult> callback);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> : IConvertMethodInvocationImposterGroupCallback<TInput, TResult>
		{
			IConvertMethodInvocationImposterGroup<TInput, TResult> Then();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IConvertMethodInvocationImposterGroup<TInput, TResult> : IConvertMethodInvocationImposterGroupCallback<TInput, TResult>
		{
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Throws<TException>()
				where TException : global::System.Exception, new();
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Throws(global::System.Exception exception);
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Throws(ConvertExceptionGeneratorDelegate<TInput, TResult> exceptionGenerator);
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Returns(ConvertDelegate<TInput, TResult> resultGenerator);
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> Returns(string value);
			IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> UseBaseImplementation();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IConvertMethodImposter
		{
			IConvertMethodImposter<TInputTarget, TResultTarget>? As<TInputTarget, TResultTarget>();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IConvertMethodImposter<TInput, TResult> : IConvertMethodImposter
		{
			string Invoke(TInput input, ConvertDelegate<TInput, TResult>? baseImplementation = null);
			bool HasMatchingInvocationImposterGroup(ConvertArguments<TInput, TResult> arguments);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ConvertInvocationVerifier<TInput, TResult>
		{
			int CallCount();
			void Called(global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IConvertMethodImposterBuilder<TInput, TResult> : IConvertMethodInvocationImposterGroup<TInput, TResult>, IConvertMethodInvocationImposterGroupCallback<TInput, TResult>, ConvertInvocationVerifier<TInput, TResult>
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ConvertMethodImposter<TInput, TResult> : IConvertMethodImposter<TInput, TResult>
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<ConvertMethodInvocationImposterGroup<TInput, TResult>> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<ConvertMethodInvocationImposterGroup<TInput, TResult>>();
			private readonly ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public ConvertMethodImposter(ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._convertMethodInvocationHistoryCollection = _convertMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			IConvertMethodImposter<TInputTarget, TResultTarget>? IConvertMethodImposter.As<TInputTarget, TResultTarget>()
			{
				if (typeof(TInputTarget).IsAssignableTo(typeof(TInput)))
				{
					return new Adapter<TInputTarget, TResultTarget>(this);
				}

				return null;
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			private class Adapter<TInputTarget, TResultTarget> : IConvertMethodImposter<TInputTarget, TResultTarget>
			{
				private readonly ConvertMethodImposter<TInput, TResult> _target;
				public Adapter(ConvertMethodImposter<TInput, TResult> target)
				{
					_target = target;
				}

				public string Invoke(TInputTarget input, ConvertDelegate<TInputTarget, TResultTarget>? baseImplementation = null)
				{
					var result = _target.Invoke(global::Imposter.Abstractions.TypeCaster.Cast<TInputTarget, TInput>(input), global::Imposter.Abstractions.TypeCaster.Cast<ConvertDelegate<TInputTarget, TResultTarget>?, ConvertDelegate<TInput, TResult>>(baseImplementation));
					return global::Imposter.Abstractions.TypeCaster.Cast<string, string>(result);
				}

				public bool HasMatchingInvocationImposterGroup(ConvertArguments<TInputTarget, TResultTarget> arguments)
				{
					return _target.HasMatchingInvocationImposterGroup(arguments.As<TInput, TResult>());
				}

				IConvertMethodImposter<TInputTarget1, TResultTarget1>? IConvertMethodImposter.As<TInputTarget1, TResultTarget1>()
				{
					throw new global::System.NotImplementedException();
				}
			}

			public bool HasMatchingInvocationImposterGroup(ConvertArguments<TInput, TResult> arguments)
			{
				return FindMatchingInvocationImposterGroup(arguments) != null;
			}

			private ConvertMethodInvocationImposterGroup<TInput, TResult>? FindMatchingInvocationImposterGroup(ConvertArguments<TInput, TResult> arguments)
			{
				foreach (var invocationImposterGroup in _invocationImposters)
				{
					if (invocationImposterGroup.ArgumentsCriteria.Matches(arguments))
						return invocationImposterGroup;
				}

				return null;
			}

			public string Invoke(TInput input, ConvertDelegate<TInput, TResult>? baseImplementation = null)
			{
				var arguments = new ConvertArguments<TInput, TResult>(input);
				var matchingInvocationImposterGroup = FindMatchingInvocationImposterGroup(arguments);
				if (matchingInvocationImposterGroup == default)
				{
					if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException("virtual string ClassWithUninferableGenericMethods.Convert<TInput, TResult>(TInput input)");
					}

					matchingInvocationImposterGroup = ConvertMethodInvocationImposterGroup<TInput, TResult>.Default;
				}

				try
				{
					var result = matchingInvocationImposterGroup.Invoke(_invocationBehavior, "virtual string ClassWithUninferableGenericMethods.Convert<TInput, TResult>(TInput input)", input, baseImplementation);
					_convertMethodInvocationHistoryCollection.Add(new ConvertMethodInvocationHistory<TInput, TResult>(arguments, result, default));
					return result;
				}
				catch (global::System.Exception ex)
				{
					_convertMethodInvocationHistoryCollection.Add(new ConvertMethodInvocationHistory<TInput, TResult>(arguments, default !, ex));
					throw;
				}
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class Builder : IConvertMethodImposterBuilder<TInput, TResult>, IConvertMethodInvocationImposterGroupContinuation<TInput, TResult>
			{
				private readonly ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection;
				private readonly ConvertArgumentsCriteria<TInput, TResult> _argumentsCriteria;
				private readonly ConvertMethodInvocationImposterGroup<TInput, TResult> _invocationImposterGroup;
				private ConvertMethodInvocationImposterGroup<TInput, TResult>.MethodInvocationImposter _currentInvocationImposter;
				public Builder(ConvertMethodImposterCollection imposterCollection, ConvertMethodInvocationHistoryCollection _convertMethodInvocationHistoryCollection, ConvertArgumentsCriteria<TInput, TResult> _argumentsCriteria)
				{
					this._convertMethodInvocationHistoryCollection = _convertMethodInvocationHistoryCollection;
					this._argumentsCriteria = _argumentsCriteria;
					this._invocationImposterGroup = new ConvertMethodInvocationImposterGroup<TInput, TResult>(_argumentsCriteria);
					ConvertMethodImposter<TInput, TResult> methodImposter = imposterCollection.AddNew<TInput, TResult>();
					methodImposter._invocationImposters.Push(_invocationImposterGroup);
					this._currentInvocationImposter = this._invocationImposterGroup.AddInvocationImposter();
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.Throws<TException>()
				{
					_currentInvocationImposter.Throws((TInput input) =>
					{
						throw new TException();
					});
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.Throws(global::System.Exception exception)
				{
					_currentInvocationImposter.Throws((TInput input) =>
					{
						throw exception;
					});
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.Throws(ConvertExceptionGeneratorDelegate<TInput, TResult> exceptionGenerator)
				{
					_currentInvocationImposter.Throws((TInput input) =>
					{
						throw exceptionGenerator.Invoke(input);
					});
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroupCallback<TInput, TResult>.Callback(ConvertCallbackDelegate<TInput, TResult> callback)
				{
					_currentInvocationImposter.Callback(callback);
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.Returns(ConvertDelegate<TInput, TResult> resultGenerator)
				{
					_currentInvocationImposter.Returns(resultGenerator);
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.Returns(string value)
				{
					_currentInvocationImposter.Returns(value);
					return this;
				}

				IConvertMethodInvocationImposterGroupContinuation<TInput, TResult> IConvertMethodInvocationImposterGroup<TInput, TResult>.UseBaseImplementation()
				{
					_currentInvocationImposter.UseBaseImplementation();
					return this;
				}

				IConvertMethodInvocationImposterGroup<TInput, TResult> IConvertMethodInvocationImposterGroupContinuation<TInput, TResult>.Then()
				{
					this._currentInvocationImposter = _invocationImposterGroup.AddInvocationImposter();
					return this;
				}

				void ConvertInvocationVerifier<TInput, TResult>.Called(global::Imposter.Abstractions.Count count)
				{
					var invocationCount = _convertMethodInvocationHistoryCollection.Count<TInput, TResult>(_argumentsCriteria);
					if (!count.Matches(invocationCount))
					{
						throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, _convertMethodInvocationHistoryCollection.ToString());
					}
				}

				int ConvertInvocationVerifier<TInput, TResult>.CallCount()
				{
					return _convertMethodInvocationHistoryCollection.Count<TInput, TResult>(_argumentsCriteria);
				}
			}
		}

		public delegate string DescribeDelegate<T>();
		public delegate void DescribeCallbackDelegate<T>();
		public delegate global::System.Exception DescribeExceptionGeneratorDelegate<T>();
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IDescribeMethodInvocationHistory
		{
			bool Matches<TTarget>();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class DescribeMethodInvocationHistory<T> : IDescribeMethodInvocationHistory
		{
			internal string? Result;
			internal global::System.Exception? Exception;
			public DescribeMethodInvocationHistory(string? Result, global::System.Exception? Exception)
			{
				this.Result = Result;
				this.Exception = Exception;
			}

			public bool Matches<TTarget>()
			{
				return typeof(string) == typeof(string);
			}

			public override string ToString()
			{
				return "Describe(" + "" + ")" + " => " + FormatValue(Result) + (Exception == null ? "" : " threw " + FormatValue(Exception));
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class DescribeMethodInvocationHistoryCollection
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<IDescribeMethodInvocationHistory> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<IDescribeMethodInvocationHistory>();
			internal void Add(IDescribeMethodInvocationHistory invocationHistory)
			{
				_invocationHistory.Push(invocationHistory);
			}

			internal int Count<T>()
			{
				return _invocationHistory.Count(it => it.Matches<T>());
			}

			public override string ToString()
			{
				return string.Join(global::System.Environment.NewLine, _invocationHistory.Select(invocation => invocation.ToString()));
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class DescribeMethodImposterCollection
		{
			private readonly DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public DescribeMethodImposterCollection(DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._describeMethodInvocationHistoryCollection = _describeMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			private readonly global::System.Collections.Concurrent.ConcurrentStack<IDescribeMethodImposter> _imposters = new global::System.Collections.Concurrent.ConcurrentStack<IDescribeMethodImposter>();
			internal DescribeMethodImposter<T> AddNew<T>()
			{
				var imposter = new DescribeMethodImposter<T>(_describeMethodInvocationHistoryCollection, _invocationBehavior);
				_imposters.Push(imposter);
				return imposter;
			}

			internal IDescribeMethodImposter<T> GetImposterWithMatchingInvocationImposterGroup<T>()
			{
				foreach (var storedImposter in _imposters)
				{
					var typedImposter = storedImposter.As<T>();
					if ((typedImposter != null) && typedImposter.HasMatchingInvocationImposterGroup())
						return typedImposter;
				}

				return new DescribeMethodImposter<T>(_describeMethodInvocationHistoryCollection, _invocationBehavior);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class DescribeMethodInvocationImposterGroup<T>
		{
			internal static DescribeMethodInvocationImposterGroup<T> Default = new DescribeMethodInvocationImposterGroup<T>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter>();
			private MethodInvocationImposter? _lastestInvocationImposter;
			public DescribeMethodInvocationImposterGroup()
			{
			}

			internal MethodInvocationImposter AddInvocationImposter()
			{
				MethodInvocationImposter invocationImposter = new MethodInvocationImposter();
				_invocationImposters.Enqueue(invocationImposter);
				return invocationImposter;
			}

			private MethodInvocationImposter? GetInvocationImposter()
			{
				if (_invocationImposters.TryDequeue(out var invocationImposter))
				{
					if (!invocationImposter.IsEmpty)
					{
						_lastestInvocationImposter = invocationImposter;
					}

					return invocationImposter;
				}

				return _lastestInvocationImposter;
			}

			public string Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, DescribeDelegate<T>? baseImplementation = null)
			{
				var invocationImposter = GetInvocationImposter();
				if (invocationImposter == null)
				{
					if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					invocationImposter = MethodInvocationImposter.Default;
				}

				return invocationImposter.Invoke(invocationBehavior, methodDisplayName, baseImplementation);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class MethodInvocationImposter
			{
				internal static MethodInvocationImposter Default;
				static MethodInvocationImposter()
				{
					Default = new MethodInvocationImposter();
					Default.Returns(DefaultResultGenerator);
				}

				private DescribeDelegate<T>? _resultGenerator;
				private readonly global::System.Collections.Concurrent.ConcurrentQueue<DescribeCallbackDelegate<T>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<DescribeCallbackDelegate<T>>();
				private bool _useBaseImplementation;
				internal bool IsEmpty => !_useBaseImplementation && ((_resultGenerator == null) && (_callbacks.Count == 0));

				public string Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, DescribeDelegate<T>? baseImplementation = null)
				{
					if (_useBaseImplementation)
					{
						_resultGenerator = baseImplementation ?? throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					if (_resultGenerator == null)
					{
						if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
						{
							throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
						}

						_resultGenerator = DefaultResultGenerator;
					}

					string result = _resultGenerator.Invoke();
					foreach (var callback in _callbacks)
					{
						callback();
					}

					return result;
				}

				internal void Callback(DescribeCallbackDelegate<T> callback)
				{
					_callbacks.Enqueue(callback);
				}

				internal void Returns(DescribeDelegate<T> resultGenerator)
				{
					_useBaseImplementation = false;
					_resultGenerator = resultGenerator;
				}

				internal void Returns(string value)
				{
					_useBaseImplementation = false;
					_resultGenerator = () =>
					{
						return value;
					};
				}

				internal void Throws(DescribeExceptionGeneratorDelegate<T> exceptionGenerator)
				{
					_useBaseImplementation = false;
					_resultGenerator = () =>
					{
						throw exceptionGenerator();
					};
				}

				internal void UseBaseImplementation()
				{
					_useBaseImplementation = true;
					_resultGenerator = null;
				}

				internal static string DefaultResultGenerator()
				{
					return default !;
				}
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IDescribeMethodInvocationImposterGroupCallback<T>
		{
			IDescribeMethodInvocationImposterGroupContinuation<T> Callback(DescribeCallbackDelegate<T> callback);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IDescribeMethodInvocationImposterGroupContinuation<T> : IDescribeMethodInvocationImposterGroupCallback<T>
		{
			IDescribeMethodInvocationImposterGroup<T> Then();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IDescribeMethodInvocationImposterGroup<T> : IDescribeMethodInvocationImposterGroupCallback<T>
		{
			IDescribeMethodInvocationImposterGroupContinuation<T> Throws<TException>()
				where TException : global::System.Exception, new();
			IDescribeMethodInvocationImposterGroupContinuation<T> Throws(global::System.Exception exception);
			IDescribeMethodInvocationImposterGroupContinuation<T> Throws(DescribeExceptionGeneratorDelegate<T> exceptionGenerator);
			IDescribeMethodInvocationImposterGroupContinuation<T> Returns(DescribeDelegate<T> resultGenerator);
			IDescribeMethodInvocationImposterGroupContinuation<T> Returns(string value);
			IDescribeMethodInvocationImposterGroupContinuation<T> UseBaseImplementation();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IDescribeMethodImposter
		{
			IDescribeMethodImposter<TTarget>? As<TTarget>();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IDescribeMethodImposter<T> : IDescribeMethodImposter
		{
			string Invoke(DescribeDelegate<T>? baseImplementation = null);
			bool HasMatchingInvocationImposterGroup();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface DescribeInvocationVerifier<T>
		{
			int CallCount();
			void Called(global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IDescribeMethodImposterBuilder<T> : IDescribeMethodInvocationImposterGroup<T>, IDescribeMethodInvocationImposterGroupCallback<T>, DescribeInvocationVerifier<T>
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class DescribeMethodImposter<T> : IDescribeMethodImposter<T>
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<DescribeMethodInvocationImposterGroup<T>> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<DescribeMethodInvocationImposterGroup<T>>();
			private readonly DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public DescribeMethodImposter(DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._describeMethodInvocationHistoryCollection = _describeMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			IDescribeMethodImposter<TTarget>? IDescribeMethodImposter.As<TTarget>()
			{
				return new Adapter<TTarget>(this);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			private class Adapter<TTarget> : IDescribeMethodImposter<TTarget>
			{
				private readonly DescribeMethodImposter<T> _target;
				public Adapter(DescribeMethodImposter<T> target)
				{
					_target = target;
				}

				public string Invoke(DescribeDelegate<TTarget>? baseImplementation = null)
				{
					var result = _target.Invoke(global::Imposter.Abstractions.TypeCaster.Cast<DescribeDelegate<TTarget>?, DescribeDelegate<T>>(baseImplementation));
					return global::Imposter.Abstractions.TypeCaster.Cast<string, string>(result);
				}

				public bool HasMatchingInvocationImposterGroup()
				{
					return _target.HasMatchingInvocationImposterGroup();
				}

				IDescribeMethodImposter<TTarget1>? IDescribeMethodImposter.As<TTarget1>()
				{
					throw new global::System.NotImplementedException();
				}
			}

			public bool HasMatchingInvocationImposterGroup()
			{
				return FindMatchingInvocationImposterGroup() != null;
			}

			private DescribeMethodInvocationImposterGroup<T>? FindMatchingInvocationImposterGroup()
			{
				if (_invocationImposters.TryPeek(out var invocationImposterGroup))
					return invocationImposterGroup;
				else
					return null;
			}

			public string Invoke(DescribeDelegate<T>? baseImplementation = null)
			{
				var matchingInvocationImposterGroup = FindMatchingInvocationImposterGroup();
				if (matchingInvocationImposterGroup == default)
				{
					if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException("virtual string ClassWithUninferableGenericMethods.Describe<T>()");
					}

					matchingInvocationImposterGroup = DescribeMethodInvocationImposterGroup<T>.Default;
				}

				try
				{
					var result = matchingInvocationImposterGroup.Invoke(_invocationBehavior, "virtual string ClassWithUninferableGenericMethods.Describe<T>()", baseImplementation);
					_describeMethodInvocationHistoryCollection.Add(new DescribeMethodInvocationHistory<T>(result, default));
					return result;
				}
				catch (global::System.Exception ex)
				{
					_describeMethodInvocationHistoryCollection.Add(new DescribeMethodInvocationHistory<T>(default !, ex));
					throw;
				}
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class Builder : IDescribeMethodImposterBuilder<T>, IDescribeMethodInvocationImposterGroupContinuation<T>
			{
				private readonly DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection;
				private readonly DescribeMethodInvocationImposterGroup<T> _invocationImposterGroup;
				private DescribeMethodInvocationImposterGroup<T>.MethodInvocationImposter _currentInvocationImposter;
				public Builder(DescribeMethodImposterCollection imposterCollection, DescribeMethodInvocationHistoryCollection _describeMethodInvocationHistoryCollection)
				{
					this._describeMethodInvocationHistoryCollection = _describeMethodInvocationHistoryCollection;
					this._invocationImposterGroup = new DescribeMethodInvocationImposterGroup<T>();
					DescribeMethodImposter<T> methodImposter = imposterCollection.AddNew<T>();
					methodImposter._invocationImposters.Push(_invocationImposterGroup);
					this._currentInvocationImposter = this._invocationImposterGroup.AddInvocationImposter();
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.Throws<TException>()
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw new TException();
					});
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.Throws(global::System.Exception exception)
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw exception;
					});
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.Throws(DescribeExceptionGeneratorDelegate<T> exceptionGenerator)
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw exceptionGenerator.Invoke();
					});
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroupCallback<T>.Callback(DescribeCallbackDelegate<T> callback)
				{
					_currentInvocationImposter.Callback(callback);
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.Returns(DescribeDelegate<T> resultGenerator)
				{
					_currentInvocationImposter.Returns(resultGenerator);
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.Returns(string value)
				{
					_currentInvocationImposter.Returns(value);
					return this;
				}

				IDescribeMethodInvocationImposterGroupContinuation<T> IDescribeMethodInvocationImposterGroup<T>.UseBaseImplementation()
				{
					_currentInvocationImposter.UseBaseImplementation();
					return this;
				}

				IDescribeMethodInvocationImposterGroup<T> IDescribeMethodInvocationImposterGroupContinuation<T>.Then()
				{
					this._currentInvocationImposter = _invocationImposterGroup.AddInvocationImposter();
					return this;
				}

				void DescribeInvocationVerifier<T>.Called(global::Imposter.Abstractions.Count count)
				{
					var invocationCount = _describeMethodInvocationHistoryCollection.Count<T>();
					if (!count.Matches(invocationCount))
					{
						throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, _describeMethodInvocationHistoryCollection.ToString());
					}
				}

				int DescribeInvocationVerifier<T>.CallCount()
				{
					return _describeMethodInvocationHistoryCollection.Count<T>();
				}
			}
		}

		public delegate void ExecuteDelegate<T>();
		public delegate void ExecuteCallbackDelegate<T>();
		public delegate global::System.Exception ExecuteExceptionGeneratorDelegate<T>();
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IExecuteMethodInvocationHistory
		{
			bool Matches<TTarget>();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ExecuteMethodInvocationHistory<T> : IExecuteMethodInvocationHistory
		{
			internal global::System.Exception? Exception;
			public ExecuteMethodInvocationHistory(global::System.Exception? Exception)
			{
				this.Exception = Exception;
			}

			public bool Matches<TTarget>()
			{
				return true;
			}

			public override string ToString()
			{
				return "Execute(" + "" + ")" + (Exception == null ? "" : " threw " + FormatValue(Exception));
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ExecuteMethodInvocationHistoryCollection
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<IExecuteMethodInvocationHistory> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<IExecuteMethodInvocationHistory>();
			internal void Add(IExecuteMethodInvocationHistory invocationHistory)
			{
				_invocationHistory.Push(invocationHistory);
			}

			internal int Count<T>()
			{
				return _invocationHistory.Count(it => it.Matches<T>());
			}

			public override string ToString()
			{
				return string.Join(global::System.Environment.NewLine, _invocationHistory.Select(invocation => invocation.ToString()));
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ExecuteMethodImposterCollection
		{
			private readonly ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public ExecuteMethodImposterCollection(ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._executeMethodInvocationHistoryCollection = _executeMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			private readonly global::System.Collections.Concurrent.ConcurrentStack<IExecuteMethodImposter> _imposters = new global::System.Collections.Concurrent.ConcurrentStack<IExecuteMethodImposter>();
			internal ExecuteMethodImposter<T> AddNew<T>()
			{
				var imposter = new ExecuteMethodImposter<T>(_executeMethodInvocationHistoryCollection, _invocationBehavior);
				_imposters.Push(imposter);
				return imposter;
			}

			internal IExecuteMethodImposter<T> GetImposterWithMatchingInvocationImposterGroup<T>()
			{
				foreach (var storedImposter in _imposters)
				{
					var typedImposter = storedImposter.As<T>();
					if ((typedImposter != null) && typedImposter.HasMatchingInvocationImposterGroup())
						return typedImposter;
				}

				return new ExecuteMethodImposter<T>(_executeMethodInvocationHistoryCollection, _invocationBehavior);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class ExecuteMethodInvocationImposterGroup<T>
		{
			internal static ExecuteMethodInvocationImposterGroup<T> Default = new ExecuteMethodInvocationImposterGroup<T>();
			private readonly global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentQueue<MethodInvocationImposter>();
			private MethodInvocationImposter? _lastestInvocationImposter;
			public ExecuteMethodInvocationImposterGroup()
			{
			}

			internal MethodInvocationImposter AddInvocationImposter()
			{
				MethodInvocationImposter invocationImposter = new MethodInvocationImposter();
				invocationImposter.UseDefaultResultGenerator();
				_invocationImposters.Enqueue(invocationImposter);
				return invocationImposter;
			}

			private MethodInvocationImposter? GetInvocationImposter()
			{
				if (_invocationImposters.TryDequeue(out var invocationImposter))
				{
					if (!invocationImposter.IsEmpty)
					{
						_lastestInvocationImposter = invocationImposter;
					}

					return invocationImposter;
				}

				return _lastestInvocationImposter;
			}

			public void Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, ExecuteDelegate<T>? baseImplementation = null)
			{
				var invocationImposter = GetInvocationImposter();
				if (invocationImposter == null)
				{
					if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					invocationImposter = MethodInvocationImposter.Default;
				}

				invocationImposter.Invoke(invocationBehavior, methodDisplayName, baseImplementation);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class MethodInvocationImposter
			{
				internal static MethodInvocationImposter Default;
				static MethodInvocationImposter()
				{
					Default = new MethodInvocationImposter();
					Default._resultGenerator = DefaultResultGenerator;
				}

				private ExecuteDelegate<T>? _resultGenerator;
				private readonly global::System.Collections.Concurrent.ConcurrentQueue<ExecuteCallbackDelegate<T>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<ExecuteCallbackDelegate<T>>();
				private bool _useBaseImplementation;
				internal bool IsEmpty => !_useBaseImplementation && ((_resultGenerator == null) && (_callbacks.Count == 0));

				public void Invoke(global::Imposter.Abstractions.ImposterMode invocationBehavior, string methodDisplayName, ExecuteDelegate<T>? baseImplementation = null)
				{
					if (_useBaseImplementation)
					{
						_resultGenerator = baseImplementation ?? throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
					}

					if (_resultGenerator == null)
					{
						if (invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
						{
							throw new global::Imposter.Abstractions.MissingImposterException(methodDisplayName);
						}

						_resultGenerator = DefaultResultGenerator;
					}

					_resultGenerator.Invoke();
					foreach (var callback in _callbacks)
					{
						callback();
					}
				}

				internal void Callback(ExecuteCallbackDelegate<T> callback)
				{
					_callbacks.Enqueue(callback);
				}

				internal void Throws(ExecuteExceptionGeneratorDelegate<T> exceptionGenerator)
				{
					_useBaseImplementation = false;
					_resultGenerator = () =>
					{
						throw exceptionGenerator();
					};
				}

				internal void UseBaseImplementation()
				{
					_useBaseImplementation = true;
					_resultGenerator = null;
				}

				internal void UseDefaultResultGenerator()
				{
					_resultGenerator = DefaultResultGenerator;
				}

				internal static void DefaultResultGenerator()
				{
				}
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IExecuteMethodInvocationImposterGroupCallback<T>
		{
			IExecuteMethodInvocationImposterGroupContinuation<T> Callback(ExecuteCallbackDelegate<T> callback);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IExecuteMethodInvocationImposterGroupContinuation<T> : IExecuteMethodInvocationImposterGroupCallback<T>
		{
			IExecuteMethodInvocationImposterGroup<T> Then();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IExecuteMethodInvocationImposterGroup<T> : IExecuteMethodInvocationImposterGroupCallback<T>
		{
			IExecuteMethodInvocationImposterGroupContinuation<T> Throws<TException>()
				where TException : global::System.Exception, new();
			IExecuteMethodInvocationImposterGroupContinuation<T> Throws(global::System.Exception exception);
			IExecuteMethodInvocationImposterGroupContinuation<T> Throws(ExecuteExceptionGeneratorDelegate<T> exceptionGenerator);
			IExecuteMethodInvocationImposterGroupContinuation<T> UseBaseImplementation();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IExecuteMethodImposter
		{
			IExecuteMethodImposter<TTarget>? As<TTarget>();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal interface IExecuteMethodImposter<T> : IExecuteMethodImposter
		{
			void Invoke(ExecuteDelegate<T>? baseImplementation = null);
			bool HasMatchingInvocationImposterGroup();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface ExecuteInvocationVerifier<T>
		{
			int CallCount();
			void Called(global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IExecuteMethodImposterBuilder<T> : IExecuteMethodInvocationImposterGroup<T>, IExecuteMethodInvocationImposterGroupCallback<T>, ExecuteInvocationVerifier<T>
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class ExecuteMethodImposter<T> : IExecuteMethodImposter<T>
		{
			private readonly global::System.Collections.Concurrent.ConcurrentStack<ExecuteMethodInvocationImposterGroup<T>> _invocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<ExecuteMethodInvocationImposterGroup<T>>();
			private readonly ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection;
			private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
			public ExecuteMethodImposter(ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection, global::Imposter.Abstractions.ImposterMode _invocationBehavior)
			{
				this._executeMethodInvocationHistoryCollection = _executeMethodInvocationHistoryCollection;
				this._invocationBehavior = _invocationBehavior;
			}

			IExecuteMethodImposter<TTarget>? IExecuteMethodImposter.As<TTarget>()
			{
				return new Adapter<TTarget>(this);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			private class Adapter<TTarget> : IExecuteMethodImposter<TTarget>
			{
				private readonly ExecuteMethodImposter<T> _target;
				public Adapter(ExecuteMethodImposter<T> target)
				{
					_target = target;
				}

				public void Invoke(ExecuteDelegate<TTarget>? baseImplementation = null)
				{
					_target.Invoke(global::Imposter.Abstractions.TypeCaster.Cast<ExecuteDelegate<TTarget>?, ExecuteDelegate<T>>(baseImplementation));
				}

				public bool HasMatchingInvocationImposterGroup()
				{
					return _target.HasMatchingInvocationImposterGroup();
				}

				IExecuteMethodImposter<TTarget1>? IExecuteMethodImposter.As<TTarget1>()
				{
					throw new global::System.NotImplementedException();
				}
			}

			public bool HasMatchingInvocationImposterGroup()
			{
				return FindMatchingInvocationImposterGroup() != null;
			}

			private ExecuteMethodInvocationImposterGroup<T>? FindMatchingInvocationImposterGroup()
			{
				if (_invocationImposters.TryPeek(out var invocationImposterGroup))
					return invocationImposterGroup;
				else
					return null;
			}

			public void Invoke(ExecuteDelegate<T>? baseImplementation = null)
			{
				var matchingInvocationImposterGroup = FindMatchingInvocationImposterGroup();
				if (matchingInvocationImposterGroup == default)
				{
					if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
					{
						throw new global::Imposter.Abstractions.MissingImposterException("virtual void ClassWithUninferableGenericMethods.Execute<T>()");
					}

					matchingInvocationImposterGroup = ExecuteMethodInvocationImposterGroup<T>.Default;
				}

				try
				{
					matchingInvocationImposterGroup.Invoke(_invocationBehavior, "virtual void ClassWithUninferableGenericMethods.Execute<T>()", baseImplementation);
					_executeMethodInvocationHistoryCollection.Add(new ExecuteMethodInvocationHistory<T>(default));
				}
				catch (global::System.Exception ex)
				{
					_executeMethodInvocationHistoryCollection.Add(new ExecuteMethodInvocationHistory<T>(ex));
					throw;
				}
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class Builder : IExecuteMethodImposterBuilder<T>, IExecuteMethodInvocationImposterGroupContinuation<T>
			{
				private readonly ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection;
				private readonly ExecuteMethodInvocationImposterGroup<T> _invocationImposterGroup;
				private ExecuteMethodInvocationImposterGroup<T>.MethodInvocationImposter _currentInvocationImposter;
				public Builder(ExecuteMethodImposterCollection imposterCollection, ExecuteMethodInvocationHistoryCollection _executeMethodInvocationHistoryCollection)
				{
					this._executeMethodInvocationHistoryCollection = _executeMethodInvocationHistoryCollection;
					this._invocationImposterGroup = new ExecuteMethodInvocationImposterGroup<T>();
					ExecuteMethodImposter<T> methodImposter = imposterCollection.AddNew<T>();
					methodImposter._invocationImposters.Push(_invocationImposterGroup);
					this._currentInvocationImposter = this._invocationImposterGroup.AddInvocationImposter();
				}

				IExecuteMethodInvocationImposterGroupContinuation<T> IExecuteMethodInvocationImposterGroup<T>.Throws<TException>()
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw new TException();
					});
					return this;
				}

				IExecuteMethodInvocationImposterGroupContinuation<T> IExecuteMethodInvocationImposterGroup<T>.Throws(global::System.Exception exception)
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw exception;
					});
					return this;
				}

				IExecuteMethodInvocationImposterGroupContinuation<T> IExecuteMethodInvocationImposterGroup<T>.Throws(ExecuteExceptionGeneratorDelegate<T> exceptionGenerator)
				{
					_currentInvocationImposter.Throws(() =>
					{
						throw exceptionGenerator.Invoke();
					});
					return this;
				}

				IExecuteMethodInvocationImposterGroupContinuation<T> IExecuteMethodInvocationImposterGroupCallback<T>.Callback(ExecuteCallbackDelegate<T> callback)
				{
					_currentInvocationImposter.Callback(callback);
					return this;
				}

				IExecuteMethodInvocationImposterGroupContinuation<T> IExecuteMethodInvocationImposterGroup<T>.UseBaseImplementation()
				{
					_currentInvocationImposter.UseBaseImplementation();
					return this;
				}

				IExecuteMethodInvocationImposterGroup<T> IExecuteMethodInvocationImposterGroupContinuation<T>.Then()
				{
					this._currentInvocationImposter = _invocationImposterGroup.AddInvocationImposter();
					return this;
				}

				void ExecuteInvocationVerifier<T>.Called(global::Imposter.Abstractions.Count count)
				{
					var invocationCount = _executeMethodInvocationHistoryCollection.Count<T>();
					if (!count.Matches(invocationCount))
					{
						throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, _executeMethodInvocationHistoryCollection.ToString());
					}
				}

				int ExecuteInvocationVerifier<T>.CallCount()
				{
					return _executeMethodInvocationHistoryCollection.Count<T>();
				}
			}
		}

		public ClassWithUninferableGenericMethodsImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
		{
			this._describeMethodImposterCollection = new DescribeMethodImposterCollection(_describeMethodInvocationHistoryCollection, invocationBehavior);
			this._convertMethodImposterCollection = new ConvertMethodImposterCollection(_convertMethodInvocationHistoryCollection, invocationBehavior);
			this._executeMethodImposterCollection = new ExecuteMethodImposterCollection(_executeMethodInvocationHistoryCollection, invocationBehavior);
			this._imposterInstance = new ImposterTargetInstance(this);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class ImposterTargetInstance : global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethods
		{
			private readonly ClassWithUninferableGenericMethodsImposter _imposter;
			internal ImposterTargetInstance(ClassWithUninferableGenericMethodsImposter _imposter) : base()
			{
				this._imposter = _imposter;
			}

			public override string Describe<T>()
			{
				if (this._imposter == null)
				{
					return base.Describe<T>();
				}

				return _imposter._describeMethodImposterCollection.GetImposterWithMatchingInvocationImposterGroup<T>().Invoke(base.Describe<T>);
			}

			public override string Convert<TInput, TResult>(TInput input)
			{
				if (this._imposter == null)
				{
					return base.Convert<TInput, TResult>(input);
				}

				return _imposter._convertMethodImposterCollection.GetImposterWithMatchingInvocationImposterGroup<TInput, TResult>(new ConvertArguments<TInput, TResult>(input)).Invoke(input, base.Convert<TInput, TResult>);
			}

			public override void Execute<T>()
			{
				if (this._imposter == null)
				{
					base.Execute<T>();
					return;
				}

				_imposter._executeMethodImposterCollection.GetImposterWithMatchingInvocationImposterGroup<T>().Invoke(base.Execute<T>);
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
	public static class ClassWithUninferableGenericMethodsImposterExtensions
	{
		extension (global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethods imposter)
		{
			public static global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethodsImposter Imposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit) => new global::Imposter.Tests.Features.ClassImpersonation.Suts.ClassWithUninferableGenericMethodsImposter(invocationBehavior);
		}
	}
}
#nullable restore
