// <auto-generated />
#nullable enable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.IndexerImpersonation;

namespace Imposter.Tests.Features.IndexerImpersonation
{
	[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
	public sealed class InParameterCopyNameCollisionIndexerClassImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass>
	{
		private ImposterTargetInstance _imposterInstance;
		global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass>.Instance()
		{
			return _imposterInstance;
		}

		private readonly IndexerIndexerBuilder _IndexerIndexer;
		public IIndexerIndexerBuilder this[global::Imposter.Abstractions.Arg<int> key, global::Imposter.Abstractions.Arg<int> keyCopy, global::Imposter.Abstractions.Arg<string> name] => new IndexerIndexerBuilder.InvocationBuilder(_IndexerIndexer, new IndexerIndexerArgumentsCriteria(key, keyCopy, name));
		public delegate string IndexerIndexerDelegate(int key, int keyCopy, string name);
		public delegate void IndexerIndexerGetterCallback(int key, int keyCopy, string name);
		public delegate void IndexerIndexerSetterCallback(int key, int keyCopy, string name, string value);
		public delegate global::System.Exception IndexerIndexerExceptionGenerator(int key, int keyCopy, string name);
		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class IndexerIndexerArguments : global::System.IEquatable<IndexerIndexerArguments>
		{
			public int key;
			public int keyCopy;
			public string name;
			internal IndexerIndexerArguments(in int key, in int keyCopy, string name)
			{
				this.key = key;
				this.keyCopy = keyCopy;
				this.name = name;
			}

			public bool Equals(IndexerIndexerArguments? other)
			{
				if (other == null)
				{
					return false;
				}

				return (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(key, other.key) && global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(keyCopy, other.keyCopy)) && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(name, other.name);
			}

			public override bool Equals(object? obj)
			{
				return obj is IndexerIndexerArguments other && Equals(other);
			}

			public override int GetHashCode()
			{
				unchecked
				{
					var hash = 17;
					hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<int>.Default.GetHashCode(key!);
					hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<int>.Default.GetHashCode(keyCopy!);
					hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<string>.Default.GetHashCode(name!);
					return hash;
				}
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class IndexerIndexerArgumentsCriteria
		{
			public global::Imposter.Abstractions.Arg<int> key;
			public global::Imposter.Abstractions.Arg<int> keyCopy;
			public global::Imposter.Abstractions.Arg<string> name;
			internal IndexerIndexerArgumentsCriteria(global::Imposter.Abstractions.Arg<int> key, global::Imposter.Abstractions.Arg<int> keyCopy, global::Imposter.Abstractions.Arg<string> name)
			{
				this.key = key;
				this.keyCopy = keyCopy;
				this.name = name;
			}

			public bool Matches(IndexerIndexerArguments arguments)
			{
				return (this.key.Matches(arguments.key) && this.keyCopy.Matches(arguments.keyCopy)) && this.name.Matches(arguments.name);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		internal class IndexerIndexerBuilder
		{
			private readonly DefaultIndexerIndexerBehaviour _IndexerDefaultIndexerBehaviour = new DefaultIndexerIndexerBehaviour();
			private readonly GetterImposter _getterImposter;
			private readonly SetterImposter _setterImposter;
			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class DefaultIndexerIndexerBehaviour
			{
				private bool _isOn = true;
				internal bool IsOn
				{
					get
					{
						return global::System.Threading.Volatile.Read(ref _isOn);
					}

					set
					{
						global::System.Threading.Volatile.Write(ref _isOn, value);
					}
				}

				internal global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArguments, string> BackingField = new global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArguments, string>();
				internal string Get(IndexerIndexerArguments arguments, global::System.Func<string>? baseImplementation = null)
				{
					if (BackingField.TryGetValue(arguments, out var value))
						return value;
					if (baseImplementation != null)
						return baseImplementation();
					return default !;
				}

				internal void Set(IndexerIndexerArguments arguments, string value)
				{
					BackingField[arguments] = value;
				}
			}

			internal IndexerIndexerBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
			{
				this._getterImposter = new GetterImposter(_IndexerDefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
				this._setterImposter = new SetterImposter(_IndexerDefaultIndexerBehaviour, invocationBehavior, propertyDisplayName);
			}

			internal IIndexerIndexerGetterBuilder CreateGetter(IndexerIndexerArgumentsCriteria criteria)
			{
				return new GetterImposter.Builder(_getterImposter, criteria);
			}

			internal IIndexerIndexerSetterBuilder CreateSetter(IndexerIndexerArgumentsCriteria criteria)
			{
				_setterImposter.MarkConfigured();
				return new SetterImposter.Builder(_setterImposter, criteria);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			internal class InvocationBuilder : IIndexerIndexerBuilder
			{
				private readonly IndexerIndexerBuilder _builder;
				private readonly IndexerIndexerArgumentsCriteria _criteria;
				internal InvocationBuilder(IndexerIndexerBuilder builder, IndexerIndexerArgumentsCriteria criteria)
				{
					this._builder = builder;
					this._criteria = criteria;
				}

				public IIndexerIndexerGetterBuilder Getter()
				{
					return _builder.CreateGetter(_criteria);
				}

				public IIndexerIndexerSetterBuilder Setter()
				{
					return _builder.CreateSetter(_criteria);
				}
			}

			internal string Get(in int key, in int keyCopy, string name, global::System.Func<string>? baseImplementation = null)
			{
				return _getterImposter.Get(key, keyCopy, name, baseImplementation);
			}

			internal void Set(in int key, in int keyCopy, string name, string value, global::System.Action? baseImplementation = null)
			{
				_setterImposter.Set(key, keyCopy, name, value, baseImplementation);
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			private sealed class GetterImposter
			{
				private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
				private readonly global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter> _getterInvocationImposters = new global::System.Collections.Concurrent.ConcurrentStack<GetterInvocationImposter>();
				private readonly global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArgumentsCriteria, GetterInvocationImposter> _setupLookup = new global::System.Collections.Concurrent.ConcurrentDictionary<IndexerIndexerArgumentsCriteria, GetterInvocationImposter>();
				private readonly global::System.Collections.Concurrent.ConcurrentStack<IndexerIndexerArguments> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<IndexerIndexerArguments>();
				private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
				private readonly string _propertyDisplayName;
				private bool _hasConfiguredReturn;
				internal GetterImposter(DefaultIndexerIndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
				{
					this._defaultBehaviour = defaultBehaviour;
					this._invocationBehavior = invocationBehavior;
					this._propertyDisplayName = propertyDisplayName;
				}

				internal string Get(in int key, in int keyCopy, string name, global::System.Func<string>? baseImplementation = null)
				{
					IndexerIndexerArguments arguments = new IndexerIndexerArguments(in key, in keyCopy, name);
					try
					{
						var getterInvocationImposter = FindGetterInvocationImposter(arguments);
						if (getterInvocationImposter is null)
						{
							EnsureGetterConfigured();
							if (_defaultBehaviour.IsOn)
								return _defaultBehaviour.Get(arguments, baseImplementation);
							if (_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit)
							{
								throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
							}
							else
							{
								return default !;
							}
						}

						return getterInvocationImposter.Invoke(arguments, baseImplementation);
					}
					finally
					{
						_invocationHistory.Push(arguments);
					}
				}

				private GetterInvocationImposter? FindGetterInvocationImposter(IndexerIndexerArguments arguments)
				{
					foreach (var getterInvocationImposter in _getterInvocationImposters)
					{
						if (getterInvocationImposter.Criteria.Matches(arguments))
						{
							return getterInvocationImposter;
						}
					}

					return null;
				}

				private GetterInvocationImposter GetOrCreate(IndexerIndexerArgumentsCriteria criteria)
				{
					return _setupLookup.GetOrAdd(criteria, CreateSetup);
					GetterInvocationImposter CreateSetup(IndexerIndexerArgumentsCriteria key)
					{
						GetterInvocationImposter getterInvocationImposter = new GetterInvocationImposter(this, _defaultBehaviour, key);
						_getterInvocationImposters.Push(getterInvocationImposter);
						return getterInvocationImposter;
					}
				}

				private void Called(IndexerIndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
				{
					int invocationCount = _invocationHistory.Count(criteria.Matches);
					if (!count.Matches(invocationCount))
					{
						var performedInvocations = new global::System.Collections.Generic.List<string>();
						foreach (var entry in _invocationHistory)
						{
							performedInvocations.Add("get " + _propertyDisplayName + "[" + string.Join(", ", new[] { FormatValue(entry.key), FormatValue(entry.keyCopy), FormatValue(entry.name) }) + "]");
						}

						throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, string.Join(global::System.Environment.NewLine, performedInvocations));
					}
				}

				internal string PropertyDisplayName => _propertyDisplayName;

				internal void MarkReturnConfigured()
				{
					global::System.Threading.Volatile.Write(ref _hasConfiguredReturn, true);
				}

				private void EnsureGetterConfigured()
				{
					if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredReturn))
					{
						throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
					}
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
				internal class Builder : IIndexerIndexerGetterBuilder, IIndexerIndexerGetterFluentBuilder
				{
					private readonly GetterImposter _imposter;
					private readonly IndexerIndexerArgumentsCriteria _criteria;
					internal Builder(GetterImposter _imposter, IndexerIndexerArgumentsCriteria _criteria)
					{
						this._imposter = _imposter;
						this._criteria = _criteria;
					}

					private GetterInvocationImposter InvocationImposter => _imposter.GetOrCreate(_criteria);

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(string value)
					{
						InvocationImposter.AddReturnValue(arguments => value);
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(global::System.Func<string> valueGenerator)
					{
						InvocationImposter.AddReturnValue(arguments => valueGenerator());
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Returns(IndexerIndexerDelegate valueGenerator)
					{
						InvocationImposter.AddReturnValue(arguments => valueGenerator(arguments.key, arguments.keyCopy, arguments.name));
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws(global::System.Exception exception)
					{
						InvocationImposter.AddReturnValue(arguments => throw exception);
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws<TException>()
					{
						InvocationImposter.AddReturnValue(arguments => throw new TException());
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.Throws(IndexerIndexerExceptionGenerator exceptionGenerator)
					{
						InvocationImposter.AddReturnValue(arguments => throw exceptionGenerator(arguments.key, arguments.keyCopy, arguments.name));
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterCallbackBuilder.Callback(IndexerIndexerGetterCallback callback)
					{
						InvocationImposter.AddCallback(callback);
						return this;
					}

					void IIndexerIndexerGetterVerifier.Called(global::Imposter.Abstractions.Count count)
					{
						_imposter.Called(_criteria, count);
					}

					IIndexerIndexerGetterFluentBuilder IIndexerIndexerGetterContinuationBuilder.Then()
					{
						return this;
					}

					IIndexerIndexerGetterContinuationBuilder IIndexerIndexerGetterOutcomeBuilder.UseBaseImplementation()
					{
						InvocationImposter.UseBaseImplementation();
						return this;
					}
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
				private sealed class GetterInvocationImposter
				{
					private readonly GetterImposter _parent;
					private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
					private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string>>();
					private readonly global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerGetterCallback> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerGetterCallback>();
					private volatile global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string>? _lastReturnValue;
					private string _propertyDisplayName;
					internal IndexerIndexerArgumentsCriteria Criteria { get; private set; }

					internal GetterInvocationImposter(GetterImposter parent, DefaultIndexerIndexerBehaviour defaultBehaviour, IndexerIndexerArgumentsCriteria criteria)
					{
						this._parent = parent;
						this._defaultBehaviour = defaultBehaviour;
						this._propertyDisplayName = parent.PropertyDisplayName;
						this.Criteria = criteria;
					}

					internal void AddReturnValue(global::System.Func<IndexerIndexerArguments, string> generator)
					{
						_defaultBehaviour.IsOn = false;
						_returnValues.Enqueue((arguments, baseImplementation) => generator(arguments));
						_parent.MarkReturnConfigured();
					}

					internal void AddCallback(IndexerIndexerGetterCallback callback)
					{
						_callbacks.Enqueue(callback);
					}

					internal string Invoke(IndexerIndexerArguments arguments, global::System.Func<string>? baseImplementation = null)
					{
						foreach (var callback in _callbacks)
						{
							callback(arguments.key, arguments.keyCopy, arguments.name);
						}

						global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string> generator = ResolveNextGenerator(arguments);
						return generator(arguments, baseImplementation);
					}

					private global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string> ResolveNextGenerator(IndexerIndexerArguments arguments)
					{
						if (_defaultBehaviour.IsOn)
						{
							return (arguments, baseImplementation) => _defaultBehaviour.Get(arguments, baseImplementation);
						}

						var nextReturnValue = NextReturnValue();
						if (nextReturnValue == null)
						{
							throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
						}

						return nextReturnValue!;
					}

					private global::System.Func<IndexerIndexerArguments, global::System.Func<string>?, string>? NextReturnValue()
					{
						if (_returnValues.IsEmpty)
						{
							return _lastReturnValue;
						}

						lock (_returnValues)
						{
							if (!_returnValues.TryPeek(out var returnValue))
							{
								return _lastReturnValue;
							}

							_lastReturnValue = returnValue;
							_returnValues.TryDequeue(out _);
							return returnValue;
						}
					}

					internal void UseBaseImplementation()
					{
						_parent.MarkReturnConfigured();
						_defaultBehaviour.IsOn = false;
						_returnValues.Enqueue((arguments, baseImplementation) =>
						{
							if (baseImplementation == null)
							{
								throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
							}

							return baseImplementation();
						});
						_lastReturnValue = null;
					}
				}
			}

			[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
			private sealed class SetterImposter
			{
				private readonly global::System.Collections.Concurrent.ConcurrentQueue<(IndexerIndexerArgumentsCriteria Criteria, IndexerIndexerSetterCallback Callback)> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<(IndexerIndexerArgumentsCriteria Criteria, IndexerIndexerSetterCallback Callback)>();
				private readonly global::System.Collections.Concurrent.ConcurrentStack<(IndexerIndexerArguments Arguments, string Value)> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<(IndexerIndexerArguments Arguments, string Value)>();
				private readonly global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerArgumentsCriteria> _baseCriteria = new global::System.Collections.Concurrent.ConcurrentQueue<IndexerIndexerArgumentsCriteria>();
				private readonly DefaultIndexerIndexerBehaviour _defaultBehaviour;
				private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
				private readonly string _propertyDisplayName;
				private bool _hasConfiguredSetter;
				internal SetterImposter(DefaultIndexerIndexerBehaviour defaultBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
				{
					this._defaultBehaviour = defaultBehaviour;
					this._invocationBehavior = invocationBehavior;
					this._propertyDisplayName = propertyDisplayName;
				}

				public void Callback(IndexerIndexerArgumentsCriteria criteria, IndexerIndexerSetterCallback callback)
				{
					_callbacks.Enqueue((criteria, callback));
				}

				public void Called(IndexerIndexerArgumentsCriteria criteria, global::Imposter.Abstractions.Count count)
				{
					int invocationCount = _invocationHistory.Count(entry => criteria.Matches(entry.Arguments));
					if (!count.Matches(invocationCount))
					{
						var performedInvocations = new global::System.Collections.Generic.List<string>();
						foreach (var entry in _invocationHistory)
						{
							performedInvocations.Add("set " + _propertyDisplayName + "[" + string.Join(", ", new[] { FormatValue(entry.Arguments.key), FormatValue(entry.Arguments.keyCopy), FormatValue(entry.Arguments.name) }) + "]" + " = " + FormatValue(entry.Value));
						}

						throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, string.Join(global::System.Environment.NewLine, performedInvocations));
					}
				}

				internal void Set(in int key, in int keyCopy, string name, string value, global::System.Action? baseImplementation = null)
				{
					EnsureSetterConfigured();
					IndexerIndexerArguments arguments = new IndexerIndexerArguments(in key, in keyCopy, name);
					_invocationHistory.Push((arguments, value));
					bool matchedCallback = false;
					foreach (var registration in _callbacks)
					{
						if (registration.Criteria.Matches(arguments))
						{
							registration.Callback(arguments.key, arguments.keyCopy, arguments.name, value);
							matchedCallback = true;
						}
					}

					bool invokedBaseImplementation = false;
					foreach (var criteria in _baseCriteria)
					{
						if (criteria.Matches(arguments))
						{
							if (baseImplementation == null)
							{
								throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
							}

							baseImplementation();
							invokedBaseImplementation = true;
							break;
						}
					}

					if (!invokedBaseImplementation && (!matchedCallback && _defaultBehaviour.IsOn))
					{
						_defaultBehaviour.Set(arguments, value);
					}
				}

				private void EnsureSetterConfigured()
				{
					if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !global::System.Threading.Volatile.Read(ref _hasConfiguredSetter))
					{
						throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
					}
				}

				internal void MarkConfigured()
				{
					global::System.Threading.Volatile.Write(ref _hasConfiguredSetter, true);
				}

				public void UseBaseImplementation(IndexerIndexerArgumentsCriteria criteria)
				{
					_baseCriteria.Enqueue(criteria);
					MarkConfigured();
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
				internal class Builder : IIndexerIndexerSetterBuilder, IIndexerIndexerSetterFluentBuilder
				{
					private readonly SetterImposter _setterImposter;
					private readonly IndexerIndexerArgumentsCriteria _criteria;
					internal Builder(SetterImposter _setterImposter, IndexerIndexerArgumentsCriteria _criteria)
					{
						this._setterImposter = _setterImposter;
						this._criteria = _criteria;
					}

					IIndexerIndexerSetterContinuationBuilder IIndexerIndexerSetterCallbackBuilder.Callback(IndexerIndexerSetterCallback callback)
					{
						_setterImposter.Callback(_criteria, callback);
						return this;
					}

					void IIndexerIndexerSetterVerifier.Called(global::Imposter.Abstractions.Count count)
					{
						_setterImposter.Called(_criteria, count);
					}

					IIndexerIndexerSetterFluentBuilder IIndexerIndexerSetterContinuationBuilder.Then()
					{
						return this;
					}

					IIndexerIndexerSetterFluentBuilder IIndexerIndexerSetterBuilder.UseBaseImplementation()
					{
						_setterImposter.UseBaseImplementation(_criteria);
						return this;
					}
				}
			}

			private static string FormatValue(object? value)
			{
				return "<" + (value?.ToString() ?? "null") + ">";
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterOutcomeBuilder
		{
			IIndexerIndexerGetterContinuationBuilder Returns(string value);
			IIndexerIndexerGetterContinuationBuilder Returns(global::System.Func<string> valueGenerator);
			IIndexerIndexerGetterContinuationBuilder Returns(IndexerIndexerDelegate valueGenerator);
			IIndexerIndexerGetterContinuationBuilder Throws(global::System.Exception exception);
			IIndexerIndexerGetterContinuationBuilder Throws<TException>()
				where TException : global::System.Exception, new();
			IIndexerIndexerGetterContinuationBuilder Throws(IndexerIndexerExceptionGenerator exceptionGenerator);
			IIndexerIndexerGetterContinuationBuilder UseBaseImplementation();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterCallbackBuilder
		{
			IIndexerIndexerGetterContinuationBuilder Callback(IndexerIndexerGetterCallback callback);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterContinuationBuilder : IIndexerIndexerGetterCallbackBuilder
		{
			IIndexerIndexerGetterFluentBuilder Then();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterVerifier
		{
			void Called(global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterFluentBuilder : IIndexerIndexerGetterOutcomeBuilder, IIndexerIndexerGetterContinuationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerGetterBuilder : IIndexerIndexerGetterOutcomeBuilder, IIndexerIndexerGetterCallbackBuilder, IIndexerIndexerGetterVerifier
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerSetterCallbackBuilder
		{
			IIndexerIndexerSetterContinuationBuilder Callback(IndexerIndexerSetterCallback callback);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerSetterContinuationBuilder : IIndexerIndexerSetterCallbackBuilder
		{
			IIndexerIndexerSetterFluentBuilder Then();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerSetterFluentBuilder : IIndexerIndexerSetterCallbackBuilder, IIndexerIndexerSetterContinuationBuilder
		{
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerSetterVerifier
		{
			void Called(global::Imposter.Abstractions.Count count);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerSetterBuilder : IIndexerIndexerSetterCallbackBuilder, IIndexerIndexerSetterVerifier
		{
			IIndexerIndexerSetterFluentBuilder UseBaseImplementation();
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		public interface IIndexerIndexerBuilder
		{
			IIndexerIndexerGetterBuilder Getter();
			IIndexerIndexerSetterBuilder Setter();
		}

		public InParameterCopyNameCollisionIndexerClassImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
		{
			this._IndexerIndexer = new IndexerIndexerBuilder(invocationBehavior, "Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass.this[in int key, in int keyCopy, string name]");
			this._imposterInstance = new ImposterTargetInstance(this);
		}

		[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
		class ImposterTargetInstance : global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass
		{
			private readonly InParameterCopyNameCollisionIndexerClassImposter _imposter;
			internal ImposterTargetInstance(InParameterCopyNameCollisionIndexerClassImposter _imposter) : base()
			{
				this._imposter = _imposter;
			}

			public override string this[in int key, in int keyCopy, string name]
			{
				get
				{
					if (this._imposter == null)
					{
						return base[key, keyCopy, name];
					}

					var keyCopy_1 = key;
					var keyCopyCopy = keyCopy;
					return _imposter._IndexerIndexer.Get(key, keyCopy, name, () => base[keyCopy_1, keyCopyCopy, name]);
				}

				set
				{
					if (this._imposter == null)
					{
						base[key, keyCopy, name] = value;
						return;
					}

					var keyCopy_1 = key;
					var keyCopyCopy = keyCopy;
					_imposter._IndexerIndexer.Set(key, keyCopy, name, value, () =>
					{
						base[keyCopy_1, keyCopyCopy, name] = value;
					});
				}
			}
		}
	}

	[global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
	public static class InParameterCopyNameCollisionIndexerClassImposterExtensions
	{
		extension (global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClass imposter)
		{
			public static global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClassImposter Imposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit) => new global::Imposter.Tests.Features.IndexerImpersonation.InParameterCopyNameCollisionIndexerClassImposter(invocationBehavior);
		}
	}
}
#nullable restore
