// <auto-generated />
#pragma warning disable nullable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using System.Collections.Concurrent;
using Sample.NamingCollision;

namespace Sample.NamingCollision
{
    [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
    public class EventBaseImplementationCollisionTargetImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Sample.NamingCollision.EventBaseImplementationCollisionTarget>
    {
        private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
        private ImposterTargetInstance _imposterInstance;
        global::Sample.NamingCollision.EventBaseImplementationCollisionTarget global::Imposter.Abstractions.IHaveImposterInstance<global::Sample.NamingCollision.EventBaseImplementationCollisionTarget>.Instance()
        {
            return _imposterInstance;
        }

        public ISubscribeEventImposterBuilder Subscribe => _Subscribe;

        private readonly SubscribeEventImposterBuilder _Subscribe;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface ISubscribeEventImposterBuilder : ISubscribeEventImposterSetupBuilder, ISubscribeEventImposterVerificationBuilder
        {
            ISubscribeEventImposterBuilder UseBaseImplementation();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface ISubscribeEventImposterSetupBuilder
        {
            ISubscribeEventImposterSetupBuilder Callback(global::System.EventHandler callback);
            ISubscribeEventImposterSetupBuilder Raise(object sender, global::System.EventArgs e);
            ISubscribeEventImposterSetupBuilder OnSubscribe(System.Action<global::System.EventHandler> interceptor);
            ISubscribeEventImposterSetupBuilder OnUnsubscribe(System.Action<global::System.EventHandler> interceptor);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface ISubscribeEventImposterVerificationBuilder
        {
            ISubscribeEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            ISubscribeEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            ISubscribeEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count);
            ISubscribeEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        internal sealed class SubscribeEventImposterBuilder : ISubscribeEventImposterBuilder, ISubscribeEventImposterSetupBuilder, ISubscribeEventImposterVerificationBuilder
        {
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _handlerOrder = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int> _handlerCounts = new System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _callbacks = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)> _history = new System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _subscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _unsubscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _subscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _unsubscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)> _handlerInvocations = new System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)>();
            private bool _useBaseImplementation;
            private readonly string _eventDisplayName = "Sample.NamingCollision.EventBaseImplementationCollisionTarget.Subscribe";
            internal SubscribeEventImposterBuilder()
            {
            }

            internal void Subscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerOrder.Enqueue(handler);
                _handlerCounts.AddOrUpdate(handler, 1, (_, count) => count + 1);
                _subscribeHistory.Enqueue(handler);
                foreach (var interceptor in _subscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            internal void Unsubscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerCounts.AddOrUpdate(handler, 0, (_, count) =>
                {
                    if (count > 0)
                    {
                        return count - 1;
                    }

                    return 0;
                });
                _unsubscribeHistory.Enqueue(handler);
                foreach (var interceptor in _unsubscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            ISubscribeEventImposterSetupBuilder ISubscribeEventImposterSetupBuilder.Callback(global::System.EventHandler callback)
            {
                ArgumentNullException.ThrowIfNull(callback);
                _callbacks.Enqueue(callback);
                return this;
            }

            ISubscribeEventImposterSetupBuilder ISubscribeEventImposterSetupBuilder.Raise(object sender, global::System.EventArgs e)
            {
                RaiseInternal(sender, e);
                return this;
            }

            ISubscribeEventImposterVerificationBuilder ISubscribeEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_subscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "subscribed");
                return this;
            }

            ISubscribeEventImposterVerificationBuilder ISubscribeEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_unsubscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "unsubscribed");
                return this;
            }

            ISubscribeEventImposterSetupBuilder ISubscribeEventImposterSetupBuilder.OnSubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _subscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            ISubscribeEventImposterSetupBuilder ISubscribeEventImposterSetupBuilder.OnUnsubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _unsubscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            ISubscribeEventImposterVerificationBuilder ISubscribeEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(senderCriteria);
                ArgumentNullException.ThrowIfNull(eCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_history, entry => senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e));
                EnsureCountMatches(actual, count, "raised");
                return this;
            }

            ISubscribeEventImposterVerificationBuilder ISubscribeEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(handlerCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_handlerInvocations, entry => handlerCriteria.Matches(entry.Handler));
                EnsureCountMatches(actual, count, "invoked");
                return this;
            }

            private void RaiseInternal(object sender, global::System.EventArgs e)
            {
                _history.Enqueue((sender, e));
                foreach (var callback in _callbacks)
                {
                    callback(sender, e);
                }

                foreach (var handler in EnumerateActiveHandlers())
                {
                    _handlerInvocations.Enqueue((handler, sender, e));
                    handler(sender, e);
                }
            }

            private System.Collections.Generic.IEnumerable<global::System.EventHandler> EnumerateActiveHandlers()
            {
                System.Collections.Generic.Dictionary<global::System.EventHandler, int> budgets = new System.Collections.Generic.Dictionary<global::System.EventHandler, int>(_handlerCounts);
                foreach (var handler in _handlerOrder)
                {
                    int remaining;
                    if (budgets.TryGetValue(handler, out remaining))
                    {
                        if (remaining > 0)
                        {
                            budgets[handler] = remaining - 1;
                            yield return handler;
                        }
                    }
                }
            }

            private static int CountMatches<T>(System.Collections.Generic.IEnumerable<T> source, System.Func<T, bool> predicate)
            {
                int count = 0;
                foreach (var item in source)
                {
                    if (predicate(item))
                    {
                        count++;
                    }
                }

                return count;
            }

            private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, string action)
            {
                if (!expected.Matches(actual))
                {
                    throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual);
                }
            }

            ISubscribeEventImposterBuilder ISubscribeEventImposterBuilder.UseBaseImplementation()
            {
                _useBaseImplementation = true;
                return this;
            }
        }

        public IThenEventImposterBuilder Then => _Then;

        private readonly ThenEventImposterBuilder _Then;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IThenEventImposterBuilder : IThenEventImposterSetupBuilder, IThenEventImposterVerificationBuilder
        {
            IThenEventImposterBuilder UseBaseImplementation();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IThenEventImposterSetupBuilder
        {
            IThenEventImposterSetupBuilder Callback(global::System.EventHandler callback);
            IThenEventImposterSetupBuilder Raise(object sender, global::System.EventArgs e);
            IThenEventImposterSetupBuilder OnSubscribe(System.Action<global::System.EventHandler> interceptor);
            IThenEventImposterSetupBuilder OnUnsubscribe(System.Action<global::System.EventHandler> interceptor);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IThenEventImposterVerificationBuilder
        {
            IThenEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IThenEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IThenEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count);
            IThenEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        internal sealed class ThenEventImposterBuilder : IThenEventImposterBuilder, IThenEventImposterSetupBuilder, IThenEventImposterVerificationBuilder
        {
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _handlerOrder = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int> _handlerCounts = new System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _callbacks = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)> _history = new System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _subscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _unsubscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _subscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _unsubscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)> _handlerInvocations = new System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)>();
            private bool _useBaseImplementation;
            private readonly string _eventDisplayName = "Sample.NamingCollision.EventBaseImplementationCollisionTarget.Then";
            internal ThenEventImposterBuilder()
            {
            }

            internal void Subscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerOrder.Enqueue(handler);
                _handlerCounts.AddOrUpdate(handler, 1, (_, count) => count + 1);
                _subscribeHistory.Enqueue(handler);
                foreach (var interceptor in _subscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            internal void Unsubscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerCounts.AddOrUpdate(handler, 0, (_, count) =>
                {
                    if (count > 0)
                    {
                        return count - 1;
                    }

                    return 0;
                });
                _unsubscribeHistory.Enqueue(handler);
                foreach (var interceptor in _unsubscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            IThenEventImposterSetupBuilder IThenEventImposterSetupBuilder.Callback(global::System.EventHandler callback)
            {
                ArgumentNullException.ThrowIfNull(callback);
                _callbacks.Enqueue(callback);
                return this;
            }

            IThenEventImposterSetupBuilder IThenEventImposterSetupBuilder.Raise(object sender, global::System.EventArgs e)
            {
                RaiseInternal(sender, e);
                return this;
            }

            IThenEventImposterVerificationBuilder IThenEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_subscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "subscribed");
                return this;
            }

            IThenEventImposterVerificationBuilder IThenEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_unsubscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "unsubscribed");
                return this;
            }

            IThenEventImposterSetupBuilder IThenEventImposterSetupBuilder.OnSubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _subscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IThenEventImposterSetupBuilder IThenEventImposterSetupBuilder.OnUnsubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _unsubscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IThenEventImposterVerificationBuilder IThenEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(senderCriteria);
                ArgumentNullException.ThrowIfNull(eCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_history, entry => senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e));
                EnsureCountMatches(actual, count, "raised");
                return this;
            }

            IThenEventImposterVerificationBuilder IThenEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(handlerCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_handlerInvocations, entry => handlerCriteria.Matches(entry.Handler));
                EnsureCountMatches(actual, count, "invoked");
                return this;
            }

            private void RaiseInternal(object sender, global::System.EventArgs e)
            {
                _history.Enqueue((sender, e));
                foreach (var callback in _callbacks)
                {
                    callback(sender, e);
                }

                foreach (var handler in EnumerateActiveHandlers())
                {
                    _handlerInvocations.Enqueue((handler, sender, e));
                    handler(sender, e);
                }
            }

            private System.Collections.Generic.IEnumerable<global::System.EventHandler> EnumerateActiveHandlers()
            {
                System.Collections.Generic.Dictionary<global::System.EventHandler, int> budgets = new System.Collections.Generic.Dictionary<global::System.EventHandler, int>(_handlerCounts);
                foreach (var handler in _handlerOrder)
                {
                    int remaining;
                    if (budgets.TryGetValue(handler, out remaining))
                    {
                        if (remaining > 0)
                        {
                            budgets[handler] = remaining - 1;
                            yield return handler;
                        }
                    }
                }
            }

            private static int CountMatches<T>(System.Collections.Generic.IEnumerable<T> source, System.Func<T, bool> predicate)
            {
                int count = 0;
                foreach (var item in source)
                {
                    if (predicate(item))
                    {
                        count++;
                    }
                }

                return count;
            }

            private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, string action)
            {
                if (!expected.Matches(actual))
                {
                    throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual);
                }
            }

            IThenEventImposterBuilder IThenEventImposterBuilder.UseBaseImplementation()
            {
                _useBaseImplementation = true;
                return this;
            }
        }

        public IUnsubscribeEventImposterBuilder Unsubscribe => _Unsubscribe;

        private readonly UnsubscribeEventImposterBuilder _Unsubscribe;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUnsubscribeEventImposterBuilder : IUnsubscribeEventImposterSetupBuilder, IUnsubscribeEventImposterVerificationBuilder
        {
            IUnsubscribeEventImposterBuilder UseBaseImplementation();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUnsubscribeEventImposterSetupBuilder
        {
            IUnsubscribeEventImposterSetupBuilder Callback(global::System.EventHandler callback);
            IUnsubscribeEventImposterSetupBuilder Raise(object sender, global::System.EventArgs e);
            IUnsubscribeEventImposterSetupBuilder OnSubscribe(System.Action<global::System.EventHandler> interceptor);
            IUnsubscribeEventImposterSetupBuilder OnUnsubscribe(System.Action<global::System.EventHandler> interceptor);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUnsubscribeEventImposterVerificationBuilder
        {
            IUnsubscribeEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IUnsubscribeEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IUnsubscribeEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count);
            IUnsubscribeEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        internal sealed class UnsubscribeEventImposterBuilder : IUnsubscribeEventImposterBuilder, IUnsubscribeEventImposterSetupBuilder, IUnsubscribeEventImposterVerificationBuilder
        {
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _handlerOrder = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int> _handlerCounts = new System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _callbacks = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)> _history = new System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _subscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _unsubscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _subscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _unsubscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)> _handlerInvocations = new System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)>();
            private bool _useBaseImplementation;
            private readonly string _eventDisplayName = "Sample.NamingCollision.EventBaseImplementationCollisionTarget.Unsubscribe";
            internal UnsubscribeEventImposterBuilder()
            {
            }

            internal void Subscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerOrder.Enqueue(handler);
                _handlerCounts.AddOrUpdate(handler, 1, (_, count) => count + 1);
                _subscribeHistory.Enqueue(handler);
                foreach (var interceptor in _subscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            internal void Unsubscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerCounts.AddOrUpdate(handler, 0, (_, count) =>
                {
                    if (count > 0)
                    {
                        return count - 1;
                    }

                    return 0;
                });
                _unsubscribeHistory.Enqueue(handler);
                foreach (var interceptor in _unsubscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            IUnsubscribeEventImposterSetupBuilder IUnsubscribeEventImposterSetupBuilder.Callback(global::System.EventHandler callback)
            {
                ArgumentNullException.ThrowIfNull(callback);
                _callbacks.Enqueue(callback);
                return this;
            }

            IUnsubscribeEventImposterSetupBuilder IUnsubscribeEventImposterSetupBuilder.Raise(object sender, global::System.EventArgs e)
            {
                RaiseInternal(sender, e);
                return this;
            }

            IUnsubscribeEventImposterVerificationBuilder IUnsubscribeEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_subscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "subscribed");
                return this;
            }

            IUnsubscribeEventImposterVerificationBuilder IUnsubscribeEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_unsubscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "unsubscribed");
                return this;
            }

            IUnsubscribeEventImposterSetupBuilder IUnsubscribeEventImposterSetupBuilder.OnSubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _subscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IUnsubscribeEventImposterSetupBuilder IUnsubscribeEventImposterSetupBuilder.OnUnsubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _unsubscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IUnsubscribeEventImposterVerificationBuilder IUnsubscribeEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(senderCriteria);
                ArgumentNullException.ThrowIfNull(eCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_history, entry => senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e));
                EnsureCountMatches(actual, count, "raised");
                return this;
            }

            IUnsubscribeEventImposterVerificationBuilder IUnsubscribeEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(handlerCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_handlerInvocations, entry => handlerCriteria.Matches(entry.Handler));
                EnsureCountMatches(actual, count, "invoked");
                return this;
            }

            private void RaiseInternal(object sender, global::System.EventArgs e)
            {
                _history.Enqueue((sender, e));
                foreach (var callback in _callbacks)
                {
                    callback(sender, e);
                }

                foreach (var handler in EnumerateActiveHandlers())
                {
                    _handlerInvocations.Enqueue((handler, sender, e));
                    handler(sender, e);
                }
            }

            private System.Collections.Generic.IEnumerable<global::System.EventHandler> EnumerateActiveHandlers()
            {
                System.Collections.Generic.Dictionary<global::System.EventHandler, int> budgets = new System.Collections.Generic.Dictionary<global::System.EventHandler, int>(_handlerCounts);
                foreach (var handler in _handlerOrder)
                {
                    int remaining;
                    if (budgets.TryGetValue(handler, out remaining))
                    {
                        if (remaining > 0)
                        {
                            budgets[handler] = remaining - 1;
                            yield return handler;
                        }
                    }
                }
            }

            private static int CountMatches<T>(System.Collections.Generic.IEnumerable<T> source, System.Func<T, bool> predicate)
            {
                int count = 0;
                foreach (var item in source)
                {
                    if (predicate(item))
                    {
                        count++;
                    }
                }

                return count;
            }

            private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, string action)
            {
                if (!expected.Matches(actual))
                {
                    throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual);
                }
            }

            IUnsubscribeEventImposterBuilder IUnsubscribeEventImposterBuilder.UseBaseImplementation()
            {
                _useBaseImplementation = true;
                return this;
            }
        }

        public IUseBaseImplementationEventImposterBuilder UseBaseImplementation => _UseBaseImplementation;

        private readonly UseBaseImplementationEventImposterBuilder _UseBaseImplementation;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUseBaseImplementationEventImposterBuilder : IUseBaseImplementationEventImposterSetupBuilder, IUseBaseImplementationEventImposterVerificationBuilder
        {
            IUseBaseImplementationEventImposterBuilder UseBaseImplementation();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUseBaseImplementationEventImposterSetupBuilder
        {
            IUseBaseImplementationEventImposterSetupBuilder Callback(global::System.EventHandler callback);
            IUseBaseImplementationEventImposterSetupBuilder Raise(object sender, global::System.EventArgs e);
            IUseBaseImplementationEventImposterSetupBuilder OnSubscribe(System.Action<global::System.EventHandler> interceptor);
            IUseBaseImplementationEventImposterSetupBuilder OnUnsubscribe(System.Action<global::System.EventHandler> interceptor);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        public interface IUseBaseImplementationEventImposterVerificationBuilder
        {
            IUseBaseImplementationEventImposterVerificationBuilder Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IUseBaseImplementationEventImposterVerificationBuilder Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count);
            IUseBaseImplementationEventImposterVerificationBuilder Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count);
            IUseBaseImplementationEventImposterVerificationBuilder HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        internal sealed class UseBaseImplementationEventImposterBuilder : IUseBaseImplementationEventImposterBuilder, IUseBaseImplementationEventImposterSetupBuilder, IUseBaseImplementationEventImposterVerificationBuilder
        {
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _handlerOrder = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int> _handlerCounts = new System.Collections.Concurrent.ConcurrentDictionary<global::System.EventHandler, int>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _callbacks = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)> _history = new System.Collections.Concurrent.ConcurrentQueue<(object sender, global::System.EventArgs e)>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _subscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler> _unsubscribeHistory = new System.Collections.Concurrent.ConcurrentQueue<global::System.EventHandler>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _subscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>> _unsubscribeInterceptors = new System.Collections.Concurrent.ConcurrentQueue<System.Action<global::System.EventHandler>>();
            private readonly System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)> _handlerInvocations = new System.Collections.Concurrent.ConcurrentQueue<(global::System.EventHandler Handler, object sender, global::System.EventArgs e)>();
            private bool _useBaseImplementation;
            private readonly string _eventDisplayName = "Sample.NamingCollision.EventBaseImplementationCollisionTarget.UseBaseImplementation";
            internal UseBaseImplementationEventImposterBuilder()
            {
            }

            internal void Subscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerOrder.Enqueue(handler);
                _handlerCounts.AddOrUpdate(handler, 1, (_, count) => count + 1);
                _subscribeHistory.Enqueue(handler);
                foreach (var interceptor in _subscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            internal void Unsubscribe(global::System.EventHandler handler, System.Action baseImplementation = null)
            {
                ArgumentNullException.ThrowIfNull(handler);
                _handlerCounts.AddOrUpdate(handler, 0, (_, count) =>
                {
                    if (count > 0)
                    {
                        return count - 1;
                    }

                    return 0;
                });
                _unsubscribeHistory.Enqueue(handler);
                foreach (var interceptor in _unsubscribeInterceptors)
                {
                    interceptor(handler);
                }

                if (_useBaseImplementation)
                {
                    if (baseImplementation != null)
                    {
                        baseImplementation();
                    }
                    else
                        throw new global::Imposter.Abstractions.MissingImposterException(_eventDisplayName + " (event)");
                }
            }

            IUseBaseImplementationEventImposterSetupBuilder IUseBaseImplementationEventImposterSetupBuilder.Callback(global::System.EventHandler callback)
            {
                ArgumentNullException.ThrowIfNull(callback);
                _callbacks.Enqueue(callback);
                return this;
            }

            IUseBaseImplementationEventImposterSetupBuilder IUseBaseImplementationEventImposterSetupBuilder.Raise(object sender, global::System.EventArgs e)
            {
                RaiseInternal(sender, e);
                return this;
            }

            IUseBaseImplementationEventImposterVerificationBuilder IUseBaseImplementationEventImposterVerificationBuilder.Subscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_subscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "subscribed");
                return this;
            }

            IUseBaseImplementationEventImposterVerificationBuilder IUseBaseImplementationEventImposterVerificationBuilder.Unsubscribed(global::Imposter.Abstractions.Arg<global::System.EventHandler> criteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(criteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_unsubscribeHistory, entry => criteria.Matches(entry));
                EnsureCountMatches(actual, count, "unsubscribed");
                return this;
            }

            IUseBaseImplementationEventImposterSetupBuilder IUseBaseImplementationEventImposterSetupBuilder.OnSubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _subscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IUseBaseImplementationEventImposterSetupBuilder IUseBaseImplementationEventImposterSetupBuilder.OnUnsubscribe(System.Action<global::System.EventHandler> interceptor)
            {
                ArgumentNullException.ThrowIfNull(interceptor);
                _unsubscribeInterceptors.Enqueue(interceptor);
                return this;
            }

            IUseBaseImplementationEventImposterVerificationBuilder IUseBaseImplementationEventImposterVerificationBuilder.Raised(global::Imposter.Abstractions.Arg<object> senderCriteria, global::Imposter.Abstractions.Arg<global::System.EventArgs> eCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(senderCriteria);
                ArgumentNullException.ThrowIfNull(eCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_history, entry => senderCriteria.Matches(entry.sender) && eCriteria.Matches(entry.e));
                EnsureCountMatches(actual, count, "raised");
                return this;
            }

            IUseBaseImplementationEventImposterVerificationBuilder IUseBaseImplementationEventImposterVerificationBuilder.HandlerInvoked(global::Imposter.Abstractions.Arg<global::System.EventHandler> handlerCriteria, global::Imposter.Abstractions.Count count)
            {
                ArgumentNullException.ThrowIfNull(handlerCriteria);
                ArgumentNullException.ThrowIfNull(count);
                int actual = CountMatches(_handlerInvocations, entry => handlerCriteria.Matches(entry.Handler));
                EnsureCountMatches(actual, count, "invoked");
                return this;
            }

            private void RaiseInternal(object sender, global::System.EventArgs e)
            {
                _history.Enqueue((sender, e));
                foreach (var callback in _callbacks)
                {
                    callback(sender, e);
                }

                foreach (var handler in EnumerateActiveHandlers())
                {
                    _handlerInvocations.Enqueue((handler, sender, e));
                    handler(sender, e);
                }
            }

            private System.Collections.Generic.IEnumerable<global::System.EventHandler> EnumerateActiveHandlers()
            {
                System.Collections.Generic.Dictionary<global::System.EventHandler, int> budgets = new System.Collections.Generic.Dictionary<global::System.EventHandler, int>(_handlerCounts);
                foreach (var handler in _handlerOrder)
                {
                    int remaining;
                    if (budgets.TryGetValue(handler, out remaining))
                    {
                        if (remaining > 0)
                        {
                            budgets[handler] = remaining - 1;
                            yield return handler;
                        }
                    }
                }
            }

            private static int CountMatches<T>(System.Collections.Generic.IEnumerable<T> source, System.Func<T, bool> predicate)
            {
                int count = 0;
                foreach (var item in source)
                {
                    if (predicate(item))
                    {
                        count++;
                    }
                }

                return count;
            }

            private static void EnsureCountMatches(int actual, global::Imposter.Abstractions.Count expected, string action)
            {
                if (!expected.Matches(actual))
                {
                    throw new global::Imposter.Abstractions.VerificationFailedException(expected, actual);
                }
            }

            IUseBaseImplementationEventImposterBuilder IUseBaseImplementationEventImposterBuilder.UseBaseImplementation()
            {
                _useBaseImplementation = true;
                return this;
            }
        }

        public EventBaseImplementationCollisionTargetImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
        {
            this._Subscribe = new SubscribeEventImposterBuilder();
            this._Then = new ThenEventImposterBuilder();
            this._Unsubscribe = new UnsubscribeEventImposterBuilder();
            this._UseBaseImplementation = new UseBaseImplementationEventImposterBuilder();
            this._imposterInstance = new ImposterTargetInstance();
            this._imposterInstance.InitializeImposter(this);
            this._invocationBehavior = invocationBehavior;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "1.0.0.0")]
        class ImposterTargetInstance : global::Sample.NamingCollision.EventBaseImplementationCollisionTarget
        {
            EventBaseImplementationCollisionTargetImposter _imposter;
            internal void InitializeImposter(EventBaseImplementationCollisionTargetImposter imposter)
            {
                _imposter = imposter;
            }

            internal ImposterTargetInstance() : base()
            {
            }

            public override event global::System.EventHandler Subscribe
            {
                add
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Subscribe.Subscribe(value, () =>
                    {
                        base.Subscribe += value;
                    });
                }

                remove
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Subscribe.Unsubscribe(value, () =>
                    {
                        base.Subscribe -= value;
                    });
                }
            }

            public override event global::System.EventHandler Then
            {
                add
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Then.Subscribe(value, () =>
                    {
                        base.Then += value;
                    });
                }

                remove
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Then.Unsubscribe(value, () =>
                    {
                        base.Then -= value;
                    });
                }
            }

            public override event global::System.EventHandler Unsubscribe
            {
                add
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Unsubscribe.Subscribe(value, () =>
                    {
                        base.Unsubscribe += value;
                    });
                }

                remove
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._Unsubscribe.Unsubscribe(value, () =>
                    {
                        base.Unsubscribe -= value;
                    });
                }
            }

            public override event global::System.EventHandler UseBaseImplementation
            {
                add
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._UseBaseImplementation.Subscribe(value, () =>
                    {
                        base.UseBaseImplementation += value;
                    });
                }

                remove
                {
                    ArgumentNullException.ThrowIfNull(value);
                    _imposter._UseBaseImplementation.Unsubscribe(value, () =>
                    {
                        base.UseBaseImplementation -= value;
                    });
                }
            }
        }
    }
}
#pragma warning restore nullable
